;; Generated by MaiaC
;; Template backend: human-readable WAT
;; Style inspired by maiawasm/assembler/tests/fixtures

(module
  (import "env" "setlocale" (func $imp_setlocale (param i32 i32) (result i32)))
  (import "env" "localeconv" (func $imp_localeconv (result i32)))
  (import "env" "printf" (func $imp_printf (param f64 f64 f64 f64 f64 f64 f64 f64) (result i32)))

  (memory $mem 1)

  (table $fn_table 1 funcref)

  ;; global __frame_ptr
  (global $__frame_ptr (mut i32) (i32.const 0))

  ;; global __stack_ptr
  (global $__stack_ptr (mut i32) (i32.const 1024))

  ;; global FILE
  (global $FILE (mut i32) (i32.const 0))

  ;; global fpos_t
  (global $fpos_t (mut i64) (i64.const 0))

  ;; global stdin
  (global $stdin (mut i32) (i32.const 0))

  ;; global stdout
  (global $stdout (mut i32) (i32.const 0))

  ;; global stderr
  (global $stderr (mut i32) (i32.const 0))

  (data (i32.const 16) "C\00")
  (data (i32.const 20) "PASS setlocale\0a\00")
  (data (i32.const 36) "PASS localeconv\0a\00")
  (data (i32.const 56) "ALL PASS\0a\00")

  (elem (table $fn_table) (i32.const 0) func $main)

  ;; function main
  (func $main (result i32)
    (local $__frame i32)
    (local $name i32)
    (local $conv i32)
    (local $__tmp_i32 i32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 80
    i32.add
    global.set $__stack_ptr
    local.get $__frame
    i32.const 0
    i32.add
    i32.const 0
    i32.const 16
    call $imp_setlocale
    local.set $__tmp_i32
    local.get $__tmp_i32
    i32.store
    local.get $__tmp_i32
    drop
    local.get $__frame
    i32.const 8
    i32.add
    call $imp_localeconv
    local.set $__tmp_i32
    local.get $__tmp_i32
    i32.store
    local.get $__tmp_i32
    drop
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.eqz
    i32.eqz
    if
      i32.const 20
      f64.convert_i32_s
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      call $imp_printf
      drop
    end
    local.get $__frame
    i32.const 8
    i32.add
    i32.load
    i32.eqz
    i32.eqz
    if (result i32)
      local.get $__frame
      i32.const 8
      i32.add
      i32.load
      i32.const 0
      i32.add
      i32.load
      i32.eqz
      i32.eqz
    else
      i32.const 0
    end
    i32.eqz
    i32.eqz
    if
      i32.const 36
      f64.convert_i32_s
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      call $imp_printf
      drop
    end
    i32.const 56
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
  )

  (export "main" (func $main))
  (export "memory" (memory $mem))
  (export "__frame_ptr" (global $__frame_ptr))
  (export "__stack_ptr" (global $__stack_ptr))
  (export "FILE" (global $FILE))
  (export "fpos_t" (global $fpos_t))
  (export "stdin" (global $stdin))
  (export "stdout" (global $stdout))
  (export "stderr" (global $stderr))
)