;; Generated by MaiaC
;; Template backend: human-readable WAT
;; Style inspired by maiawasm/assembler/tests/fixtures

(module
  (import "env" "printf" (func $imp_printf (param f64 f64 f64 f64 f64 f64 f64 f64) (result i32)))
  (import "env" "strcmp" (func $imp_strcmp (param i32 i32) (result i32)))

  (memory $mem 1)

  (table $fn_table 1 funcref)

  ;; global __frame_ptr
  (global $__frame_ptr (mut i32) (i32.const 0))

  ;; global __stack_ptr
  (global $__stack_ptr (mut i32) (i32.const 1024))

  ;; global stdin
  (global $stdin (mut i32) (i32.const 0))

  ;; global stdout
  (global $stdout (mut i32) (i32.const 0))

  ;; global stderr
  (global $stderr (mut i32) (i32.const 0))

  (data (i32.const 16) "PASS object_macro\0a\00")
  (data (i32.const 36) "PASS function_macro\0a\00")
  (data (i32.const 60) "PASS nested_macro\0a\00")
  (data (i32.const 80) "PASS conditional_macro\0a\00")
  (data (i32.const 104) "macro\00")
  (data (i32.const 112) "PASS include_and_string\0a\00")
  (data (i32.const 140) "ALL PASS\0a\00")

  (elem (table $fn_table) (i32.const 0) func $main)

  ;; function main
  (func $main (result i32)
    (local $sum_value i32)
    (local $calc_value i32)
    (local $square_value i32)
    (local $conditional_value i32)
    i32.const 40
    i32.const 2
    i32.add
    local.tee $sum_value
    drop
    i32.const 7
    i32.const 11
    i32.add
    local.tee $calc_value
    drop
    i32.const 3
    i32.const 3
    i32.mul
    local.tee $square_value
    drop
    i32.const 7
    i32.const 11
    i32.add
    local.tee $conditional_value
    drop
    local.get $sum_value
    i32.const 42
    i32.eq
    i32.eqz
    i32.eqz
    if
      i32.const 16
      f64.convert_i32_s
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      call $imp_printf
      drop
    end
    local.get $calc_value
    i32.const 18
    i32.eq
    i32.eqz
    i32.eqz
    if
      i32.const 36
      f64.convert_i32_s
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      call $imp_printf
      drop
    end
    local.get $square_value
    i32.const 9
    i32.eq
    i32.eqz
    i32.eqz
    if
      i32.const 60
      f64.convert_i32_s
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      call $imp_printf
      drop
    end
    local.get $conditional_value
    i32.const 18
    i32.eq
    i32.eqz
    i32.eqz
    if
      i32.const 80
      f64.convert_i32_s
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      call $imp_printf
      drop
    end
    i32.const 104
    i32.const 104
    call $imp_strcmp
    i32.const 0
    i32.eq
    i32.eqz
    i32.eqz
    if
      i32.const 112
      f64.convert_i32_s
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      call $imp_printf
      drop
    end
    i32.const 140
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 0
    return
    i32.const 0
    return
  )

  (export "main" (func $main))
  (export "memory" (memory $mem))
  (export "__frame_ptr" (global $__frame_ptr))
  (export "__stack_ptr" (global $__stack_ptr))
  (export "stdin" (global $stdin))
  (export "stdout" (global $stdout))
  (export "stderr" (global $stderr))
)