;; Generated by MaiaC
;; Template backend: human-readable WAT
;; Style inspired by maiawasm/assembler/tests/fixtures

(module
  (import "env" "printf" (func $imp_printf (param f64 f64 f64 f64 f64 f64 f64 f64) (result i32)))
  (import "env" "scanf" (func $imp_scanf (param i32 i32 i32 i32 i32 i32 i32 i32) (result i32)))

  (memory $mem 1)

  (table $fn_table 3 funcref)

  ;; global __frame_ptr
  (global $__frame_ptr (mut i32) (i32.const 0))

  ;; global __stack_ptr
  (global $__stack_ptr (mut i32) (i32.const 1024))

  ;; global stdin
  (global $stdin (mut i32) (i32.const 0))

  ;; global stdout
  (global $stdout (mut i32) (i32.const 0))

  ;; global stderr
  (global $stderr (mut i32) (i32.const 0))

  (data (i32.const 16) "Enter the temperature in Fahrenheit as an integer: \00")
  (data (i32.const 68) "%d\00")
  (data (i32.const 72) "The temperature in Celsius is %d.\0a\00")
  (data (i32.const 108) "Enter the temperature in Fahrenheit as a real number: \00")
  (data (i32.const 164) "%f\00")
  (data (i32.const 168) "The temperature in Celsius is %f.\0a\00")

  (elem (table $fn_table) (i32.const 0) func $fahrenheit_to_celsius_float $fahrenheit_to_celsius_int $main)

  ;; function fahrenheit_to_celsius_float
  (func $fahrenheit_to_celsius_float (param $t f32) (result f32)
    local.get $t
    f32.const 32
    f32.sub
    f32.const 5
    f32.mul
    f32.const 9
    f32.div
    return
    f32.const 0
    return
  )

  ;; function fahrenheit_to_celsius_int
  (func $fahrenheit_to_celsius_int (param $t i32) (result i32)
    local.get $t
    i32.const 32
    i32.sub
    i32.const 5
    i32.mul
    i32.const 9
    i32.div_s
    return
    i32.const 0
    return
  )

  ;; function main
  (func $main (result i32)
    (local $__frame i32)
    (local $t1 i32)
    (local $t2 f32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 8
    i32.add
    global.set $__stack_ptr
    i32.const 16
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 68
    local.get $__frame
    i32.const 0
    i32.add
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    call $imp_scanf
    drop
    i32.const 72
    f64.convert_i32_s
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    call $fahrenheit_to_celsius_int
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 108
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 164
    local.get $__frame
    i32.const 4
    i32.add
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    call $imp_scanf
    drop
    i32.const 168
    f64.convert_i32_s
    local.get $__frame
    i32.const 4
    i32.add
    f32.load
    call $fahrenheit_to_celsius_float
    f64.promote_f32
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
  )

  (export "fahrenheit_to_celsius_float" (func $fahrenheit_to_celsius_float))
  (export "fahrenheit_to_celsius_int" (func $fahrenheit_to_celsius_int))
  (export "main" (func $main))
  (export "memory" (memory $mem))
  (export "__frame_ptr" (global $__frame_ptr))
  (export "__stack_ptr" (global $__stack_ptr))
  (export "stdin" (global $stdin))
  (export "stdout" (global $stdout))
  (export "stderr" (global $stderr))
)