;; Generated by MaiaC
;; Template backend: human-readable WAT
;; Style inspired by maiawasm/assembler/tests/fixtures

(module
  (import "env" "__console__log" (func $imp___console__log (param i32)))
  (import "env" "__Math__sqrt" (func $imp___Math__sqrt (param f64) (result f64)))
  (import "env" "__Math__floor" (func $imp___Math__floor (param f64) (result i32)))

  (memory $mem 1)

  (table $fn_table 1 funcref)

  ;; global __frame_ptr
  (global $__frame_ptr (mut i32) (i32.const 0))

  ;; global __stack_ptr
  (global $__stack_ptr (mut i32) (i32.const 1024))

  (data (i32.const 16) "PASS host_console_log\00")
  (data (i32.const 40) "PASS host_math_sqrt\00")
  (data (i32.const 60) "ALL PASS\00")

  (elem (table $fn_table) (i32.const 0) func $main)

  ;; function main
  (func $main (result i32)
    (local $root f64)
    i32.const 16
    call $imp___console__log
    f64.const 144
    call $imp___Math__sqrt
    local.tee $root
    drop
    local.get $root
    call $imp___Math__floor
    i32.const 12
    i32.eq
    i32.eqz
    i32.eqz
    if
      i32.const 40
      call $imp___console__log
    end
    i32.const 60
    call $imp___console__log
    i32.const 0
    return
    i32.const 0
    return
  )

  (export "main" (func $main))
  (export "memory" (memory $mem))
  (export "__frame_ptr" (global $__frame_ptr))
  (export "__stack_ptr" (global $__stack_ptr))
)