;; Generated by MaiaC
;; Template backend: human-readable WAT
;; Style inspired by maiawasm/assembler/tests/fixtures

(module
  (import "env" "printf" (func $imp_printf (param f64 f64 f64 f64 f64 f64 f64 f64) (result i32)))
  (import "env" "scanf" (func $imp_scanf (param i32 i32 i32 i32 i32 i32 i32 i32) (result i32)))

  (memory $mem 1)

  (table $fn_table 2 funcref)

  ;; global __frame_ptr
  (global $__frame_ptr (mut i32) (i32.const 0))

  ;; global __stack_ptr
  (global $__stack_ptr (mut i32) (i32.const 1024))

  ;; global stdin
  (global $stdin (mut i32) (i32.const 0))

  ;; global stdout
  (global $stdout (mut i32) (i32.const 0))

  ;; global stderr
  (global $stderr (mut i32) (i32.const 0))

  ;; global VEHICLE_CAR
  (global $VEHICLE_CAR i32 (i32.const 0))

  ;; global VEHICLE_TRUCK
  (global $VEHICLE_TRUCK i32 (i32.const 1))

  ;; global VEHICLE_TRACTOR
  (global $VEHICLE_TRACTOR i32 (i32.const 2))

  (data (i32.const 16) "Silver\00")
  (data (i32.const 24) "XL\00")
  (data (i32.const 28) "Red\00")
  (data (i32.const 32) "X\00")
  (data (i32.const 36) "Blue\00")
  (data (i32.const 44) "MF 3400\00")
  (data (i32.const 52) "Build your vehicle:\0a\00")
  (data (i32.const 76) "Would you like to buy a car (1), truck (2) or tractor (3)? \00")
  (data (i32.const 136) "%d\00")
  (data (i32.const 140) "\0aWould you like a vehicle with air conditioning (y/n)? \00")
  (data (i32.const 196) " %c\00")
  (data (i32.const 200) "\0aWould you like a vehicle with power steering (y/n)? \00")
  (data (i32.const 256) "Invalid option!\00")
  (data (i32.const 272) "The vehicle %s costs $%.0f.\0a\00")

  (elem (table $fn_table) (i32.const 0) func $automobile_init $main)

  ;; function automobile_init
  (func $automobile_init (param $a i32) (param $type i32) (param $color i32) (param $year i32) (param $model i32) (param $engine_size f32) (param $price f32) (param $ac f32) (param $steering f32)
    (local $__frame i32)
    (local $i i32)
    (local $__tmp_i32 i32)
    (local $__tmp_addr i32)
    (local $__tmp_old_i32 i32)
    (local $__tmp_f32 f32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 136
    i32.add
    global.set $__stack_ptr
    local.get $__frame
    i32.const 0
    i32.add
    local.get $a
    i32.store
    local.get $__frame
    i32.const 96
    i32.add
    local.get $type
    i32.store
    local.get $__frame
    i32.const 100
    i32.add
    local.get $color
    i32.store
    local.get $__frame
    i32.const 104
    i32.add
    local.get $year
    i32.store
    local.get $__frame
    i32.const 108
    i32.add
    local.get $model
    i32.store
    local.get $__frame
    i32.const 112
    i32.add
    local.get $engine_size
    f32.store
    local.get $__frame
    i32.const 116
    i32.add
    local.get $price
    f32.store
    local.get $__frame
    i32.const 120
    i32.add
    local.get $ac
    f32.store
    local.get $__frame
    i32.const 124
    i32.add
    local.get $steering
    f32.store
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 0
    i32.add
    local.get $__frame
    i32.const 96
    i32.add
    i32.load
    local.set $__tmp_i32
    local.get $__tmp_i32
    i32.store
    local.get $__tmp_i32
    drop
    local.get $__frame
    i32.const 128
    i32.add
    i32.const 0
    local.set $__tmp_i32
    local.get $__tmp_i32
    i32.store
    local.get $__tmp_i32
    drop
    block $automobile_init_for_exit_0
      loop $automobile_init_for_loop_2
        local.get $__frame
        i32.const 100
        i32.add
        i32.load
        local.get $__frame
        i32.const 128
        i32.add
        i32.load
        i32.const 1
        i32.mul
        i32.add
        i32.load8_u
        i32.eqz
        i32.eqz
        if (result i32)
          local.get $__frame
          i32.const 128
          i32.add
          i32.load
          i32.const 31
          i32.lt_s
          i32.eqz
          i32.eqz
        else
          i32.const 0
        end
        i32.eqz
        i32.eqz
        i32.eqz
        br_if $automobile_init_for_exit_0
        block $automobile_init_for_continue_1
          local.get $__frame
          i32.const 0
          i32.add
          i32.load
          local.get $__frame
          i32.const 128
          i32.add
          i32.load
          i32.const 4
          i32.mul
          i32.add
          local.get $__frame
          i32.const 100
          i32.add
          i32.load
          local.get $__frame
          i32.const 128
          i32.add
          i32.load
          i32.const 1
          i32.mul
          i32.add
          i32.load8_u
          local.set $__tmp_i32
          local.get $__tmp_i32
          i32.store
          local.get $__tmp_i32
          drop
        end
        local.get $__frame
        i32.const 128
        i32.add
        local.tee $__tmp_addr
        i32.load
        local.tee $__tmp_old_i32
        i32.const 1
        i32.add
        local.set $__tmp_i32
        local.get $__tmp_addr
        local.get $__tmp_i32
        i32.store
        local.get $__tmp_old_i32
        drop
        br $automobile_init_for_loop_2
      end
    end
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    local.get $__frame
    i32.const 128
    i32.add
    i32.load
    i32.const 4
    i32.mul
    i32.add
    i32.const 0
    local.set $__tmp_i32
    local.get $__tmp_i32
    i32.store
    local.get $__tmp_i32
    drop
    local.get $__frame
    i32.const 128
    i32.add
    i32.const 0
    local.set $__tmp_i32
    local.get $__tmp_i32
    i32.store
    local.get $__tmp_i32
    drop
    block $automobile_init_for_exit_3
      loop $automobile_init_for_loop_5
        local.get $__frame
        i32.const 108
        i32.add
        i32.load
        local.get $__frame
        i32.const 128
        i32.add
        i32.load
        i32.const 1
        i32.mul
        i32.add
        i32.load8_u
        i32.eqz
        i32.eqz
        if (result i32)
          local.get $__frame
          i32.const 128
          i32.add
          i32.load
          i32.const 31
          i32.lt_s
          i32.eqz
          i32.eqz
        else
          i32.const 0
        end
        i32.eqz
        i32.eqz
        i32.eqz
        br_if $automobile_init_for_exit_3
        block $automobile_init_for_continue_4
          local.get $__frame
          i32.const 0
          i32.add
          i32.load
          local.get $__frame
          i32.const 128
          i32.add
          i32.load
          i32.const 4
          i32.mul
          i32.add
          local.get $__frame
          i32.const 108
          i32.add
          i32.load
          local.get $__frame
          i32.const 128
          i32.add
          i32.load
          i32.const 1
          i32.mul
          i32.add
          i32.load8_u
          local.set $__tmp_i32
          local.get $__tmp_i32
          i32.store
          local.get $__tmp_i32
          drop
        end
        local.get $__frame
        i32.const 128
        i32.add
        local.tee $__tmp_addr
        i32.load
        local.tee $__tmp_old_i32
        i32.const 1
        i32.add
        local.set $__tmp_i32
        local.get $__tmp_addr
        local.get $__tmp_i32
        i32.store
        local.get $__tmp_old_i32
        drop
        br $automobile_init_for_loop_5
      end
    end
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    local.get $__frame
    i32.const 128
    i32.add
    i32.load
    i32.const 4
    i32.mul
    i32.add
    i32.const 0
    local.set $__tmp_i32
    local.get $__tmp_i32
    i32.store
    local.get $__tmp_i32
    drop
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 40
    i32.add
    local.get $__frame
    i32.const 104
    i32.add
    i32.load
    local.set $__tmp_i32
    local.get $__tmp_i32
    i32.store
    local.get $__tmp_i32
    drop
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 80
    i32.add
    local.get $__frame
    i32.const 112
    i32.add
    f32.load
    local.set $__tmp_f32
    local.get $__tmp_f32
    f32.store
    local.get $__tmp_f32
    drop
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 84
    i32.add
    local.get $__frame
    i32.const 116
    i32.add
    f32.load
    local.set $__tmp_f32
    local.get $__tmp_f32
    f32.store
    local.get $__tmp_f32
    drop
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 88
    i32.add
    local.get $__frame
    i32.const 120
    i32.add
    f32.load
    local.set $__tmp_f32
    local.get $__tmp_f32
    f32.store
    local.get $__tmp_f32
    drop
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 92
    i32.add
    local.get $__frame
    i32.const 124
    i32.add
    f32.load
    local.set $__tmp_f32
    local.get $__tmp_f32
    f32.store
    local.get $__tmp_f32
    drop
  )

  ;; function main
  (func $main (result i32)
    (local $__frame i32)
    (local $etios i32)
    (local $actros i32)
    (local $mf3400 i32)
    (local $vehicle_type i32)
    (local $want_ac i32)
    (local $want_steering i32)
    (local $total_price f32)
    (local $model i32)
    (local $i i32)
    (local $__tmp_f32 f32)
    (local $__tmp_i8 i32)
    (local $main___switch_value_1 i32)
    (local $main___switch_matched_2 i32)
    (local $__tmp_i32 i32)
    (local $__tmp_addr i32)
    (local $__tmp_old_i32 i32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 344
    i32.add
    global.set $__stack_ptr
    local.get $__frame
    i32.const 0
    i32.add
    global.get $VEHICLE_CAR
    i32.const 16
    i32.const 2021
    i32.const 24
    f32.const 1.4
    f32.const 50000
    f32.const 2000
    f32.const 3000
    call $automobile_init
    local.get $__frame
    i32.const 96
    i32.add
    global.get $VEHICLE_TRUCK
    i32.const 28
    i32.const 2022
    i32.const 32
    f32.const 6
    f32.const 500000
    f32.const 20000
    f32.const 30000
    call $automobile_init
    local.get $__frame
    i32.const 192
    i32.add
    global.get $VEHICLE_TRACTOR
    i32.const 36
    i32.const 2022
    i32.const 44
    f32.const 3
    f32.const 75000
    f32.const 3000
    f32.const 4000
    call $automobile_init
    local.get $__frame
    i32.const 300
    i32.add
    f32.const 0
    local.set $__tmp_f32
    local.get $__tmp_f32
    f32.store
    local.get $__tmp_f32
    drop
    local.get $__frame
    i32.const 304
    i32.add
    i32.const 0
    i32.const 1
    i32.mul
    i32.add
    i32.const 0
    local.set $__tmp_i8
    local.get $__tmp_i8
    i32.store8
    local.get $__tmp_i8
    drop
    i32.const 52
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 76
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 136
    local.get $__frame
    i32.const 288
    i32.add
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    call $imp_scanf
    drop
    i32.const 140
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 196
    local.get $__frame
    i32.const 292
    i32.add
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    call $imp_scanf
    drop
    i32.const 200
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 196
    local.get $__frame
    i32.const 296
    i32.add
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    call $imp_scanf
    drop
    local.get $__frame
    i32.const 288
    i32.add
    i32.load
    local.set $main___switch_value_1
    i32.const 0
    local.set $main___switch_matched_2
    block $main_switch_exit_0
      local.get $main___switch_matched_2
      if
        local.get $__frame
        i32.const 336
        i32.add
        i32.const 0
        local.set $__tmp_i32
        local.get $__tmp_i32
        i32.store
        local.get $__tmp_i32
        drop
        block $main_for_exit_3
          loop $main_for_loop_5
            local.get $__frame
            i32.const 0
            i32.add
            local.get $__frame
            i32.const 336
            i32.add
            i32.load
            i32.const 4
            i32.mul
            i32.add
            i32.load
            i32.eqz
            i32.eqz
            i32.eqz
            br_if $main_for_exit_3
            block $main_for_continue_4
              local.get $__frame
              i32.const 304
              i32.add
              local.get $__frame
              i32.const 336
              i32.add
              i32.load
              i32.const 1
              i32.mul
              i32.add
              local.get $__frame
              i32.const 0
              i32.add
              local.get $__frame
              i32.const 336
              i32.add
              i32.load
              i32.const 4
              i32.mul
              i32.add
              i32.load
              local.set $__tmp_i8
              local.get $__tmp_i8
              i32.store8
              local.get $__tmp_i8
              drop
            end
            local.get $__frame
            i32.const 336
            i32.add
            local.tee $__tmp_addr
            i32.load
            local.tee $__tmp_old_i32
            i32.const 1
            i32.add
            local.set $__tmp_i32
            local.get $__tmp_addr
            local.get $__tmp_i32
            i32.store
            local.get $__tmp_old_i32
            drop
            br $main_for_loop_5
          end
        end
        local.get $__frame
        i32.const 304
        i32.add
        local.get $__frame
        i32.const 336
        i32.add
        i32.load
        i32.const 1
        i32.mul
        i32.add
        i32.const 0
        local.set $__tmp_i8
        local.get $__tmp_i8
        i32.store8
        local.get $__tmp_i8
        drop
        local.get $__frame
        i32.const 300
        i32.add
        local.get $__frame
        i32.const 0
        i32.add
        i32.const 84
        i32.add
        f32.load
        local.set $__tmp_f32
        local.get $__tmp_f32
        f32.store
        local.get $__tmp_f32
        drop
        local.get $__frame
        i32.const 292
        i32.add
        i32.load
        i32.const 121
        i32.eq
        i32.eqz
        i32.eqz
        if
          local.get $__frame
          i32.const 300
          i32.add
          local.get $__frame
          i32.const 300
          i32.add
          f32.load
          local.get $__frame
          i32.const 0
          i32.add
          i32.const 88
          i32.add
          f32.load
          f32.add
          local.set $__tmp_f32
          local.get $__tmp_f32
          f32.store
          local.get $__tmp_f32
          drop
        end
        local.get $__frame
        i32.const 296
        i32.add
        i32.load
        i32.const 121
        i32.eq
        i32.eqz
        i32.eqz
        if
          local.get $__frame
          i32.const 300
          i32.add
          local.get $__frame
          i32.const 300
          i32.add
          f32.load
          local.get $__frame
          i32.const 0
          i32.add
          i32.const 92
          i32.add
          f32.load
          f32.add
          local.set $__tmp_f32
          local.get $__tmp_f32
          f32.store
          local.get $__tmp_f32
          drop
        end
        br $main_switch_exit_0
      else
        local.get $main___switch_value_1
        i32.const 1
        i32.eq
        if
          i32.const 1
          local.set $main___switch_matched_2
          local.get $__frame
          i32.const 336
          i32.add
          i32.const 0
          local.set $__tmp_i32
          local.get $__tmp_i32
          i32.store
          local.get $__tmp_i32
          drop
          block $main_for_exit_3
            loop $main_for_loop_5
              local.get $__frame
              i32.const 0
              i32.add
              local.get $__frame
              i32.const 336
              i32.add
              i32.load
              i32.const 4
              i32.mul
              i32.add
              i32.load
              i32.eqz
              i32.eqz
              i32.eqz
              br_if $main_for_exit_3
              block $main_for_continue_4
                local.get $__frame
                i32.const 304
                i32.add
                local.get $__frame
                i32.const 336
                i32.add
                i32.load
                i32.const 1
                i32.mul
                i32.add
                local.get $__frame
                i32.const 0
                i32.add
                local.get $__frame
                i32.const 336
                i32.add
                i32.load
                i32.const 4
                i32.mul
                i32.add
                i32.load
                local.set $__tmp_i8
                local.get $__tmp_i8
                i32.store8
                local.get $__tmp_i8
                drop
              end
              local.get $__frame
              i32.const 336
              i32.add
              local.tee $__tmp_addr
              i32.load
              local.tee $__tmp_old_i32
              i32.const 1
              i32.add
              local.set $__tmp_i32
              local.get $__tmp_addr
              local.get $__tmp_i32
              i32.store
              local.get $__tmp_old_i32
              drop
              br $main_for_loop_5
            end
          end
          local.get $__frame
          i32.const 304
          i32.add
          local.get $__frame
          i32.const 336
          i32.add
          i32.load
          i32.const 1
          i32.mul
          i32.add
          i32.const 0
          local.set $__tmp_i8
          local.get $__tmp_i8
          i32.store8
          local.get $__tmp_i8
          drop
          local.get $__frame
          i32.const 300
          i32.add
          local.get $__frame
          i32.const 0
          i32.add
          i32.const 84
          i32.add
          f32.load
          local.set $__tmp_f32
          local.get $__tmp_f32
          f32.store
          local.get $__tmp_f32
          drop
          local.get $__frame
          i32.const 292
          i32.add
          i32.load
          i32.const 121
          i32.eq
          i32.eqz
          i32.eqz
          if
            local.get $__frame
            i32.const 300
            i32.add
            local.get $__frame
            i32.const 300
            i32.add
            f32.load
            local.get $__frame
            i32.const 0
            i32.add
            i32.const 88
            i32.add
            f32.load
            f32.add
            local.set $__tmp_f32
            local.get $__tmp_f32
            f32.store
            local.get $__tmp_f32
            drop
          end
          local.get $__frame
          i32.const 296
          i32.add
          i32.load
          i32.const 121
          i32.eq
          i32.eqz
          i32.eqz
          if
            local.get $__frame
            i32.const 300
            i32.add
            local.get $__frame
            i32.const 300
            i32.add
            f32.load
            local.get $__frame
            i32.const 0
            i32.add
            i32.const 92
            i32.add
            f32.load
            f32.add
            local.set $__tmp_f32
            local.get $__tmp_f32
            f32.store
            local.get $__tmp_f32
            drop
          end
          br $main_switch_exit_0
        end
      end
      local.get $main___switch_matched_2
      if
        local.get $__frame
        i32.const 336
        i32.add
        i32.const 0
        local.set $__tmp_i32
        local.get $__tmp_i32
        i32.store
        local.get $__tmp_i32
        drop
        block $main_for_exit_6
          loop $main_for_loop_8
            local.get $__frame
            i32.const 96
            i32.add
            local.get $__frame
            i32.const 336
            i32.add
            i32.load
            i32.const 4
            i32.mul
            i32.add
            i32.load
            i32.eqz
            i32.eqz
            i32.eqz
            br_if $main_for_exit_6
            block $main_for_continue_7
              local.get $__frame
              i32.const 304
              i32.add
              local.get $__frame
              i32.const 336
              i32.add
              i32.load
              i32.const 1
              i32.mul
              i32.add
              local.get $__frame
              i32.const 96
              i32.add
              local.get $__frame
              i32.const 336
              i32.add
              i32.load
              i32.const 4
              i32.mul
              i32.add
              i32.load
              local.set $__tmp_i8
              local.get $__tmp_i8
              i32.store8
              local.get $__tmp_i8
              drop
            end
            local.get $__frame
            i32.const 336
            i32.add
            local.tee $__tmp_addr
            i32.load
            local.tee $__tmp_old_i32
            i32.const 1
            i32.add
            local.set $__tmp_i32
            local.get $__tmp_addr
            local.get $__tmp_i32
            i32.store
            local.get $__tmp_old_i32
            drop
            br $main_for_loop_8
          end
        end
        local.get $__frame
        i32.const 304
        i32.add
        local.get $__frame
        i32.const 336
        i32.add
        i32.load
        i32.const 1
        i32.mul
        i32.add
        i32.const 0
        local.set $__tmp_i8
        local.get $__tmp_i8
        i32.store8
        local.get $__tmp_i8
        drop
        local.get $__frame
        i32.const 300
        i32.add
        local.get $__frame
        i32.const 96
        i32.add
        i32.const 84
        i32.add
        f32.load
        local.set $__tmp_f32
        local.get $__tmp_f32
        f32.store
        local.get $__tmp_f32
        drop
        local.get $__frame
        i32.const 292
        i32.add
        i32.load
        i32.const 121
        i32.eq
        i32.eqz
        i32.eqz
        if
          local.get $__frame
          i32.const 300
          i32.add
          local.get $__frame
          i32.const 300
          i32.add
          f32.load
          local.get $__frame
          i32.const 96
          i32.add
          i32.const 88
          i32.add
          f32.load
          f32.add
          local.set $__tmp_f32
          local.get $__tmp_f32
          f32.store
          local.get $__tmp_f32
          drop
        end
        local.get $__frame
        i32.const 296
        i32.add
        i32.load
        i32.const 121
        i32.eq
        i32.eqz
        i32.eqz
        if
          local.get $__frame
          i32.const 300
          i32.add
          local.get $__frame
          i32.const 300
          i32.add
          f32.load
          local.get $__frame
          i32.const 96
          i32.add
          i32.const 92
          i32.add
          f32.load
          f32.add
          local.set $__tmp_f32
          local.get $__tmp_f32
          f32.store
          local.get $__tmp_f32
          drop
        end
        br $main_switch_exit_0
      else
        local.get $main___switch_value_1
        i32.const 2
        i32.eq
        if
          i32.const 1
          local.set $main___switch_matched_2
          local.get $__frame
          i32.const 336
          i32.add
          i32.const 0
          local.set $__tmp_i32
          local.get $__tmp_i32
          i32.store
          local.get $__tmp_i32
          drop
          block $main_for_exit_6
            loop $main_for_loop_8
              local.get $__frame
              i32.const 96
              i32.add
              local.get $__frame
              i32.const 336
              i32.add
              i32.load
              i32.const 4
              i32.mul
              i32.add
              i32.load
              i32.eqz
              i32.eqz
              i32.eqz
              br_if $main_for_exit_6
              block $main_for_continue_7
                local.get $__frame
                i32.const 304
                i32.add
                local.get $__frame
                i32.const 336
                i32.add
                i32.load
                i32.const 1
                i32.mul
                i32.add
                local.get $__frame
                i32.const 96
                i32.add
                local.get $__frame
                i32.const 336
                i32.add
                i32.load
                i32.const 4
                i32.mul
                i32.add
                i32.load
                local.set $__tmp_i8
                local.get $__tmp_i8
                i32.store8
                local.get $__tmp_i8
                drop
              end
              local.get $__frame
              i32.const 336
              i32.add
              local.tee $__tmp_addr
              i32.load
              local.tee $__tmp_old_i32
              i32.const 1
              i32.add
              local.set $__tmp_i32
              local.get $__tmp_addr
              local.get $__tmp_i32
              i32.store
              local.get $__tmp_old_i32
              drop
              br $main_for_loop_8
            end
          end
          local.get $__frame
          i32.const 304
          i32.add
          local.get $__frame
          i32.const 336
          i32.add
          i32.load
          i32.const 1
          i32.mul
          i32.add
          i32.const 0
          local.set $__tmp_i8
          local.get $__tmp_i8
          i32.store8
          local.get $__tmp_i8
          drop
          local.get $__frame
          i32.const 300
          i32.add
          local.get $__frame
          i32.const 96
          i32.add
          i32.const 84
          i32.add
          f32.load
          local.set $__tmp_f32
          local.get $__tmp_f32
          f32.store
          local.get $__tmp_f32
          drop
          local.get $__frame
          i32.const 292
          i32.add
          i32.load
          i32.const 121
          i32.eq
          i32.eqz
          i32.eqz
          if
            local.get $__frame
            i32.const 300
            i32.add
            local.get $__frame
            i32.const 300
            i32.add
            f32.load
            local.get $__frame
            i32.const 96
            i32.add
            i32.const 88
            i32.add
            f32.load
            f32.add
            local.set $__tmp_f32
            local.get $__tmp_f32
            f32.store
            local.get $__tmp_f32
            drop
          end
          local.get $__frame
          i32.const 296
          i32.add
          i32.load
          i32.const 121
          i32.eq
          i32.eqz
          i32.eqz
          if
            local.get $__frame
            i32.const 300
            i32.add
            local.get $__frame
            i32.const 300
            i32.add
            f32.load
            local.get $__frame
            i32.const 96
            i32.add
            i32.const 92
            i32.add
            f32.load
            f32.add
            local.set $__tmp_f32
            local.get $__tmp_f32
            f32.store
            local.get $__tmp_f32
            drop
          end
          br $main_switch_exit_0
        end
      end
      local.get $main___switch_matched_2
      if
        local.get $__frame
        i32.const 336
        i32.add
        i32.const 0
        local.set $__tmp_i32
        local.get $__tmp_i32
        i32.store
        local.get $__tmp_i32
        drop
        block $main_for_exit_9
          loop $main_for_loop_11
            local.get $__frame
            i32.const 192
            i32.add
            local.get $__frame
            i32.const 336
            i32.add
            i32.load
            i32.const 4
            i32.mul
            i32.add
            i32.load
            i32.eqz
            i32.eqz
            i32.eqz
            br_if $main_for_exit_9
            block $main_for_continue_10
              local.get $__frame
              i32.const 304
              i32.add
              local.get $__frame
              i32.const 336
              i32.add
              i32.load
              i32.const 1
              i32.mul
              i32.add
              local.get $__frame
              i32.const 192
              i32.add
              local.get $__frame
              i32.const 336
              i32.add
              i32.load
              i32.const 4
              i32.mul
              i32.add
              i32.load
              local.set $__tmp_i8
              local.get $__tmp_i8
              i32.store8
              local.get $__tmp_i8
              drop
            end
            local.get $__frame
            i32.const 336
            i32.add
            local.tee $__tmp_addr
            i32.load
            local.tee $__tmp_old_i32
            i32.const 1
            i32.add
            local.set $__tmp_i32
            local.get $__tmp_addr
            local.get $__tmp_i32
            i32.store
            local.get $__tmp_old_i32
            drop
            br $main_for_loop_11
          end
        end
        local.get $__frame
        i32.const 304
        i32.add
        local.get $__frame
        i32.const 336
        i32.add
        i32.load
        i32.const 1
        i32.mul
        i32.add
        i32.const 0
        local.set $__tmp_i8
        local.get $__tmp_i8
        i32.store8
        local.get $__tmp_i8
        drop
        local.get $__frame
        i32.const 300
        i32.add
        local.get $__frame
        i32.const 192
        i32.add
        i32.const 84
        i32.add
        f32.load
        local.set $__tmp_f32
        local.get $__tmp_f32
        f32.store
        local.get $__tmp_f32
        drop
        local.get $__frame
        i32.const 292
        i32.add
        i32.load
        i32.const 121
        i32.eq
        i32.eqz
        i32.eqz
        if
          local.get $__frame
          i32.const 300
          i32.add
          local.get $__frame
          i32.const 300
          i32.add
          f32.load
          local.get $__frame
          i32.const 192
          i32.add
          i32.const 88
          i32.add
          f32.load
          f32.add
          local.set $__tmp_f32
          local.get $__tmp_f32
          f32.store
          local.get $__tmp_f32
          drop
        end
        local.get $__frame
        i32.const 296
        i32.add
        i32.load
        i32.const 121
        i32.eq
        i32.eqz
        i32.eqz
        if
          local.get $__frame
          i32.const 300
          i32.add
          local.get $__frame
          i32.const 300
          i32.add
          f32.load
          local.get $__frame
          i32.const 192
          i32.add
          i32.const 92
          i32.add
          f32.load
          f32.add
          local.set $__tmp_f32
          local.get $__tmp_f32
          f32.store
          local.get $__tmp_f32
          drop
        end
        br $main_switch_exit_0
      else
        local.get $main___switch_value_1
        i32.const 3
        i32.eq
        if
          i32.const 1
          local.set $main___switch_matched_2
          local.get $__frame
          i32.const 336
          i32.add
          i32.const 0
          local.set $__tmp_i32
          local.get $__tmp_i32
          i32.store
          local.get $__tmp_i32
          drop
          block $main_for_exit_9
            loop $main_for_loop_11
              local.get $__frame
              i32.const 192
              i32.add
              local.get $__frame
              i32.const 336
              i32.add
              i32.load
              i32.const 4
              i32.mul
              i32.add
              i32.load
              i32.eqz
              i32.eqz
              i32.eqz
              br_if $main_for_exit_9
              block $main_for_continue_10
                local.get $__frame
                i32.const 304
                i32.add
                local.get $__frame
                i32.const 336
                i32.add
                i32.load
                i32.const 1
                i32.mul
                i32.add
                local.get $__frame
                i32.const 192
                i32.add
                local.get $__frame
                i32.const 336
                i32.add
                i32.load
                i32.const 4
                i32.mul
                i32.add
                i32.load
                local.set $__tmp_i8
                local.get $__tmp_i8
                i32.store8
                local.get $__tmp_i8
                drop
              end
              local.get $__frame
              i32.const 336
              i32.add
              local.tee $__tmp_addr
              i32.load
              local.tee $__tmp_old_i32
              i32.const 1
              i32.add
              local.set $__tmp_i32
              local.get $__tmp_addr
              local.get $__tmp_i32
              i32.store
              local.get $__tmp_old_i32
              drop
              br $main_for_loop_11
            end
          end
          local.get $__frame
          i32.const 304
          i32.add
          local.get $__frame
          i32.const 336
          i32.add
          i32.load
          i32.const 1
          i32.mul
          i32.add
          i32.const 0
          local.set $__tmp_i8
          local.get $__tmp_i8
          i32.store8
          local.get $__tmp_i8
          drop
          local.get $__frame
          i32.const 300
          i32.add
          local.get $__frame
          i32.const 192
          i32.add
          i32.const 84
          i32.add
          f32.load
          local.set $__tmp_f32
          local.get $__tmp_f32
          f32.store
          local.get $__tmp_f32
          drop
          local.get $__frame
          i32.const 292
          i32.add
          i32.load
          i32.const 121
          i32.eq
          i32.eqz
          i32.eqz
          if
            local.get $__frame
            i32.const 300
            i32.add
            local.get $__frame
            i32.const 300
            i32.add
            f32.load
            local.get $__frame
            i32.const 192
            i32.add
            i32.const 88
            i32.add
            f32.load
            f32.add
            local.set $__tmp_f32
            local.get $__tmp_f32
            f32.store
            local.get $__tmp_f32
            drop
          end
          local.get $__frame
          i32.const 296
          i32.add
          i32.load
          i32.const 121
          i32.eq
          i32.eqz
          i32.eqz
          if
            local.get $__frame
            i32.const 300
            i32.add
            local.get $__frame
            i32.const 300
            i32.add
            f32.load
            local.get $__frame
            i32.const 192
            i32.add
            i32.const 92
            i32.add
            f32.load
            f32.add
            local.set $__tmp_f32
            local.get $__tmp_f32
            f32.store
            local.get $__tmp_f32
            drop
          end
          br $main_switch_exit_0
        end
      end
      local.get $main___switch_matched_2
      if
        i32.const 256
        f64.convert_i32_s
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        call $imp_printf
        drop
        i32.const 0
        local.get $__parent_frame
        global.set $__frame_ptr
        local.get $__frame
        global.set $__stack_ptr
        return
      else
        i32.const 1
        if
          i32.const 1
          local.set $main___switch_matched_2
          i32.const 256
          f64.convert_i32_s
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          call $imp_printf
          drop
          i32.const 0
          local.get $__parent_frame
          global.set $__frame_ptr
          local.get $__frame
          global.set $__stack_ptr
          return
        end
      end
    end
    i32.const 272
    f64.convert_i32_s
    local.get $__frame
    i32.const 304
    i32.add
    f64.convert_i32_s
    local.get $__frame
    i32.const 300
    i32.add
    f32.load
    f64.promote_f32
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
  )

  (export "automobile_init" (func $automobile_init))
  (export "main" (func $main))
  (export "memory" (memory $mem))
  (export "__frame_ptr" (global $__frame_ptr))
  (export "__stack_ptr" (global $__stack_ptr))
  (export "stdin" (global $stdin))
  (export "stdout" (global $stdout))
  (export "stderr" (global $stderr))
)