;; Generated by MaiaC
;; Template backend: human-readable WAT
;; Style inspired by maiawasm/assembler/tests/fixtures

(module
  (import "env" "printf" (func $imp_printf (param f64 f64 f64 f64 f64 f64 f64 f64) (result i32)))

  (memory $mem 1)

  (table $fn_table 4 funcref)

  ;; global __frame_ptr
  (global $__frame_ptr (mut i32) (i32.const 0))

  ;; global __stack_ptr
  (global $__stack_ptr (mut i32) (i32.const 1024))

  ;; global stdin
  (global $stdin (mut i32) (i32.const 0))

  ;; global stdout
  (global $stdout (mut i32) (i32.const 0))

  ;; global stderr
  (global $stderr (mut i32) (i32.const 0))

  (data (i32.const 16) "%s ate %s.\0a\00")
  (data (i32.const 28) "Phyllis\00")
  (data (i32.const 36) "Dino\00")
  (data (i32.const 44) "Peter\00")
  (data (i32.const 52) "Rex\00")
  (data (i32.const 56) "The name of dinosaur dino is %s.\0a\00")
  (data (i32.const 92) "The name of dinosaur peter is %s.\0a\00")
  (data (i32.const 128) "The name of dinosaur rex is %s.\0a\00")

  (elem (table $fn_table) (i32.const 0) func $lifeform_init $dinosaur_init $dinosaur_eat $main)

  ;; function lifeform_init
  (func $lifeform_init (param $lf i32) (param $name i32)
    (local $__frame i32)
    (local $i i32)
    (local $__tmp_i32 i32)
    (local $__tmp_i8 i32)
    (local $__tmp_addr i32)
    (local $__tmp_old_i32 i32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 64
    i32.add
    global.set $__stack_ptr
    local.get $__frame
    i32.const 0
    i32.add
    local.get $lf
    i32.store
    local.get $__frame
    i32.const 52
    i32.add
    local.get $name
    i32.store
    local.get $__frame
    i32.const 56
    i32.add
    i32.const 0
    local.set $__tmp_i32
    local.get $__tmp_i32
    i32.store
    local.get $__tmp_i32
    drop
    block $lifeform_init_for_exit_0
      loop $lifeform_init_for_loop_2
        local.get $__frame
        i32.const 52
        i32.add
        i32.load
        local.get $__frame
        i32.const 56
        i32.add
        i32.load
        i32.const 1
        i32.mul
        i32.add
        i32.load8_u
        i32.eqz
        i32.eqz
        if (result i32)
          local.get $__frame
          i32.const 56
          i32.add
          i32.load
          i32.const 49
          i32.lt_s
          i32.eqz
          i32.eqz
        else
          i32.const 0
        end
        i32.eqz
        i32.eqz
        i32.eqz
        br_if $lifeform_init_for_exit_0
        block $lifeform_init_for_continue_1
          local.get $__frame
          i32.const 0
          i32.add
          i32.load
          i32.const 0
          i32.add
          local.get $__frame
          i32.const 56
          i32.add
          i32.load
          i32.const 1
          i32.mul
          i32.add
          local.get $__frame
          i32.const 52
          i32.add
          i32.load
          local.get $__frame
          i32.const 56
          i32.add
          i32.load
          i32.const 1
          i32.mul
          i32.add
          i32.load8_u
          local.set $__tmp_i8
          local.get $__tmp_i8
          i32.store8
          local.get $__tmp_i8
          drop
        end
        local.get $__frame
        i32.const 56
        i32.add
        local.tee $__tmp_addr
        i32.load
        local.tee $__tmp_old_i32
        i32.const 1
        i32.add
        local.set $__tmp_i32
        local.get $__tmp_addr
        local.get $__tmp_i32
        i32.store
        local.get $__tmp_old_i32
        drop
        br $lifeform_init_for_loop_2
      end
    end
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 0
    i32.add
    local.get $__frame
    i32.const 56
    i32.add
    i32.load
    i32.const 1
    i32.mul
    i32.add
    i32.const 0
    local.set $__tmp_i8
    local.get $__tmp_i8
    i32.store8
    local.get $__tmp_i8
    drop
  )

  ;; function dinosaur_init
  (func $dinosaur_init (param $d i32) (param $name i32)
    (local $__frame i32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 56
    i32.add
    global.set $__stack_ptr
    local.get $__frame
    i32.const 0
    i32.add
    local.get $d
    i32.store
    local.get $__frame
    i32.const 52
    i32.add
    local.get $name
    i32.store
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 0
    i32.add
    local.get $__frame
    i32.const 52
    i32.add
    i32.load
    call $lifeform_init
  )

  ;; function dinosaur_eat
  (func $dinosaur_eat (param $predator i32) (param $prey i32)
    (local $__frame i32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 104
    i32.add
    global.set $__stack_ptr
    local.get $__frame
    i32.const 0
    i32.add
    local.get $predator
    i32.store
    local.get $__frame
    i32.const 52
    i32.add
    local.get $prey
    i32.store
    i32.const 16
    f64.convert_i32_s
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 0
    i32.add
    i32.const 0
    i32.add
    f64.convert_i32_s
    local.get $__frame
    i32.const 52
    i32.add
    i32.load
    i32.const 0
    i32.add
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
  )

  ;; function main
  (func $main (result i32)
    (local $__frame i32)
    (local $plant i32)
    (local $dino i32)
    (local $peter i32)
    (local $rex i32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 208
    i32.add
    global.set $__stack_ptr
    local.get $__frame
    i32.const 0
    i32.add
    i32.const 28
    call $lifeform_init
    local.get $__frame
    i32.const 52
    i32.add
    i32.const 36
    call $dinosaur_init
    local.get $__frame
    i32.const 104
    i32.add
    i32.const 44
    call $dinosaur_init
    local.get $__frame
    i32.const 156
    i32.add
    i32.const 52
    call $dinosaur_init
    i32.const 56
    f64.convert_i32_s
    local.get $__frame
    i32.const 52
    i32.add
    i32.const 0
    i32.add
    i32.const 0
    i32.add
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 92
    f64.convert_i32_s
    local.get $__frame
    i32.const 104
    i32.add
    i32.const 0
    i32.add
    i32.const 0
    i32.add
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 128
    f64.convert_i32_s
    local.get $__frame
    i32.const 156
    i32.add
    i32.const 0
    i32.add
    i32.const 0
    i32.add
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    local.get $__frame
    i32.const 52
    i32.add
    local.get $__frame
    i32.const 0
    i32.add
    call $dinosaur_eat
    local.get $__frame
    i32.const 156
    i32.add
    local.get $__frame
    i32.const 52
    i32.add
    i32.const 0
    i32.add
    call $dinosaur_eat
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
  )

  (export "lifeform_init" (func $lifeform_init))
  (export "dinosaur_init" (func $dinosaur_init))
  (export "dinosaur_eat" (func $dinosaur_eat))
  (export "main" (func $main))
  (export "memory" (memory $mem))
  (export "__frame_ptr" (global $__frame_ptr))
  (export "__stack_ptr" (global $__stack_ptr))
  (export "stdin" (global $stdin))
  (export "stdout" (global $stdout))
  (export "stderr" (global $stderr))
)