;; Generated by MaiaC
;; Template backend: human-readable WAT
;; Style inspired by maiawasm/assembler/tests/fixtures

(module
  (import "env" "printf" (func $imp_printf (param f64 f64 f64 f64 f64 f64 f64 f64) (result i32)))

  (memory $mem 1)

  (table $fn_table 5 funcref)

  ;; global __frame_ptr
  (global $__frame_ptr (mut i32) (i32.const 0))

  ;; global __stack_ptr
  (global $__stack_ptr (mut i32) (i32.const 1024))

  ;; global ERA_AUSTRALOPITHECUS
  (global $ERA_AUSTRALOPITHECUS i32 (i32.const 0))

  ;; global ERA_HOMO_HABILIS
  (global $ERA_HOMO_HABILIS i32 (i32.const 1))

  ;; global ERA_HOMO_ERECTUS
  (global $ERA_HOMO_ERECTUS i32 (i32.const 2))

  ;; global ERA_HOMO_SAPIENS
  (global $ERA_HOMO_SAPIENS i32 (i32.const 3))

  ;; global ERA_HOMO_NEANDERTHALENSIS
  (global $ERA_HOMO_NEANDERTHALENSIS i32 (i32.const 4))

  ;; global stdin
  (global $stdin (mut i32) (i32.const 0))

  ;; global stdout
  (global $stdout (mut i32) (i32.const 0))

  ;; global stderr
  (global $stderr (mut i32) (i32.const 0))

  (data (i32.const 16) "%s fought with %s.\0a\00")
  (data (i32.const 36) "%s said \22%s\22.\0a\00")
  (data (i32.const 52) "%s said \22%s\22 to %s.\0a\00")
  (data (i32.const 76) "\04\00\00\00")
  (data (i32.const 80) "Fred\00")
  (data (i32.const 88) "\03\00\00\00")
  (data (i32.const 92) "Adam\00")
  (data (i32.const 100) "What a lovely day!\00")
  (data (i32.const 120) "Who are you?\00")

  (elem (table $fn_table) (i32.const 0) func $human_init $human_fight $human_say $human_say_to $main)

  ;; function human_init
  (func $human_init (param $h i32) (param $era i32) (param $name i32)
    (local $__frame i32)
    (local $i i32)
    (local $__tmp_i32 i32)
    (local $__tmp_i8 i32)
    (local $__tmp_addr i32)
    (local $__tmp_old_i32 i32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 72
    i32.add
    global.set $__stack_ptr
    local.get $__frame
    i32.const 0
    i32.add
    local.get $h
    i32.store
    local.get $__frame
    i32.const 56
    i32.add
    local.get $era
    i32.store
    local.get $__frame
    i32.const 60
    i32.add
    local.get $name
    i32.store
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 0
    i32.add
    local.get $__frame
    i32.const 56
    i32.add
    i32.load
    local.set $__tmp_i32
    local.get $__tmp_i32
    i32.store
    local.get $__tmp_i32
    drop
    local.get $__frame
    i32.const 64
    i32.add
    i32.const 0
    local.set $__tmp_i32
    local.get $__tmp_i32
    i32.store
    local.get $__tmp_i32
    drop
    block $human_init_for_exit_0
      loop $human_init_for_loop_2
        local.get $__frame
        i32.const 60
        i32.add
        i32.load
        local.get $__frame
        i32.const 64
        i32.add
        i32.load
        i32.const 1
        i32.mul
        i32.add
        i32.load8_u
        i32.eqz
        i32.eqz
        if (result i32)
          local.get $__frame
          i32.const 64
          i32.add
          i32.load
          i32.const 49
          i32.lt_s
          i32.eqz
          i32.eqz
        else
          i32.const 0
        end
        i32.eqz
        i32.eqz
        i32.eqz
        br_if $human_init_for_exit_0
        block $human_init_for_continue_1
          local.get $__frame
          i32.const 0
          i32.add
          i32.load
          i32.const 4
          i32.add
          local.get $__frame
          i32.const 64
          i32.add
          i32.load
          i32.const 1
          i32.mul
          i32.add
          local.get $__frame
          i32.const 60
          i32.add
          i32.load
          local.get $__frame
          i32.const 64
          i32.add
          i32.load
          i32.const 1
          i32.mul
          i32.add
          i32.load8_u
          local.set $__tmp_i8
          local.get $__tmp_i8
          i32.store8
          local.get $__tmp_i8
          drop
        end
        local.get $__frame
        i32.const 64
        i32.add
        local.tee $__tmp_addr
        i32.load
        local.tee $__tmp_old_i32
        i32.const 1
        i32.add
        local.set $__tmp_i32
        local.get $__tmp_addr
        local.get $__tmp_i32
        i32.store
        local.get $__tmp_old_i32
        drop
        br $human_init_for_loop_2
      end
    end
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 4
    i32.add
    local.get $__frame
    i32.const 64
    i32.add
    i32.load
    i32.const 1
    i32.mul
    i32.add
    i32.const 0
    local.set $__tmp_i8
    local.get $__tmp_i8
    i32.store8
    local.get $__tmp_i8
    drop
  )

  ;; function human_fight
  (func $human_fight (param $attacker i32) (param $defender i32)
    (local $__frame i32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 112
    i32.add
    global.set $__stack_ptr
    local.get $__frame
    i32.const 0
    i32.add
    local.get $attacker
    i32.store
    local.get $__frame
    i32.const 56
    i32.add
    local.get $defender
    i32.store
    i32.const 16
    f64.convert_i32_s
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 4
    i32.add
    f64.convert_i32_s
    local.get $__frame
    i32.const 56
    i32.add
    i32.load
    i32.const 4
    i32.add
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
  )

  ;; function human_say
  (func $human_say (param $speaker i32) (param $s i32)
    (local $__frame i32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 64
    i32.add
    global.set $__stack_ptr
    local.get $__frame
    i32.const 0
    i32.add
    local.get $speaker
    i32.store
    local.get $__frame
    i32.const 56
    i32.add
    local.get $s
    i32.store
    i32.const 36
    f64.convert_i32_s
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 4
    i32.add
    f64.convert_i32_s
    local.get $__frame
    i32.const 56
    i32.add
    i32.load
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
  )

  ;; function human_say_to
  (func $human_say_to (param $speaker i32) (param $s i32) (param $listener i32)
    (local $__frame i32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 120
    i32.add
    global.set $__stack_ptr
    local.get $__frame
    i32.const 0
    i32.add
    local.get $speaker
    i32.store
    local.get $__frame
    i32.const 56
    i32.add
    local.get $s
    i32.store
    local.get $__frame
    i32.const 60
    i32.add
    local.get $listener
    i32.store
    i32.const 52
    f64.convert_i32_s
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 4
    i32.add
    f64.convert_i32_s
    local.get $__frame
    i32.const 56
    i32.add
    i32.load
    f64.convert_i32_s
    local.get $__frame
    i32.const 60
    i32.add
    i32.load
    i32.const 4
    i32.add
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
  )

  ;; function main
  (func $main (result i32)
    (local $__frame i32)
    (local $fred i32)
    (local $adam i32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 112
    i32.add
    global.set $__stack_ptr
    local.get $__frame
    i32.const 0
    i32.add
    i32.const 76
    i32.load
    i32.const 80
    call $human_init
    local.get $__frame
    i32.const 56
    i32.add
    i32.const 88
    i32.load
    i32.const 92
    call $human_init
    local.get $__frame
    i32.const 56
    i32.add
    i32.const 100
    call $human_say
    local.get $__frame
    i32.const 56
    i32.add
    i32.const 120
    local.get $__frame
    i32.const 0
    i32.add
    call $human_say_to
    local.get $__frame
    i32.const 0
    i32.add
    local.get $__frame
    i32.const 56
    i32.add
    call $human_fight
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
  )

  (export "human_init" (func $human_init))
  (export "human_fight" (func $human_fight))
  (export "human_say" (func $human_say))
  (export "human_say_to" (func $human_say_to))
  (export "main" (func $main))
  (export "memory" (memory $mem))
  (export "__frame_ptr" (global $__frame_ptr))
  (export "__stack_ptr" (global $__stack_ptr))
  (export "stdin" (global $stdin))
  (export "stdout" (global $stdout))
  (export "stderr" (global $stderr))
)