;; Generated by MaiaC
;; Template backend: human-readable WAT
;; Style inspired by maiawasm/assembler/tests/fixtures

(module
  (table $fn_table 1 funcref)

  (elem (table $fn_table) (i32.const 0) func $test_entry)

  ;; function test_entry
  (func $test_entry (result i32)
    (local $a i32)
    (local $b i32)
    (local $r i32)
    i32.const 10
    local.set $a
    i32.const 20
    local.set $b
    i32.const 0
    local.set $r
    local.get $r
    local.get $a
    local.get $b
    i32.add
    i32.add
    local.tee $r
    drop
    local.get $r
    local.get $b
    local.get $a
    i32.sub
    i32.add
    local.tee $r
    drop
    local.get $r
    local.get $a
    i32.const 2
    i32.mul
    i32.add
    local.tee $r
    drop
    local.get $r
    local.get $b
    i32.const 2
    i32.div_s
    i32.add
    local.tee $r
    drop
    local.get $r
    local.get $b
    i32.const 7
    i32.rem_s
    i32.add
    local.tee $r
    drop
    local.get $r
    local.get $a
    local.get $b
    i32.lt_s
    i32.eqz
    i32.eqz
    if (result i32)
      i32.const 1
    else
      i32.const 0
    end
    i32.add
    local.tee $r
    drop
    local.get $r
    local.get $a
    local.get $b
    i32.eq
    i32.eqz
    i32.eqz
    if (result i32)
      i32.const 10
    else
      i32.const 0
    end
    i32.add
    local.tee $r
    drop
    local.get $r
    local.get $a
    i32.eqz
    i32.eqz
    if (result i32)
      local.get $b
      i32.eqz
      i32.eqz
    else
      i32.const 0
    end
    i32.eqz
    i32.eqz
    if (result i32)
      i32.const 100
    else
      i32.const 0
    end
    i32.add
    local.tee $r
    drop
    local.get $r
    local.get $a
    local.get $b
    i32.add
    i32.const 3
    i32.mul
    i32.const 2
    i32.div_s
    i32.add
    local.tee $r
    drop
    local.get $r
    return
    i32.const 0
    return
  )

  (export "test_entry" (func $test_entry))
)