;; Generated by MaiaC
;; Template backend: human-readable WAT
;; Style inspired by maiawasm/assembler/tests/fixtures

(module
  (table $fn_table 1 funcref)

  (elem (table $fn_table) (i32.const 0) func $add_one)

  ;; function add_one
  (func $add_one (param $value i32) (result i32)
    local.get $value
    i32.const 1
    i32.add
    return
    i32.const 0
    return
  )

  (export "add_one" (func $add_one))
)