;; Generated by MaiaC
;; Template backend: human-readable WAT
;; Style inspired by maiawasm/assembler/tests/fixtures

(module
  (import "env" "__console__log" (func $imp___console__log (param i32)))
  (import "env" "__console__error" (func $imp___console__error (param i32)))
  (import "env" "__Math__sqrt" (func $imp___Math__sqrt (param f64) (result f64)))
  (import "env" "__Math__cbrt" (func $imp___Math__cbrt (param f64) (result f64)))
  (import "env" "__Math__abs" (func $imp___Math__abs (param f64) (result f64)))
  (import "env" "__Math__ceil" (func $imp___Math__ceil (param f64) (result f64)))
  (import "env" "__Math__floor" (func $imp___Math__floor (param f64) (result f64)))
  (import "env" "__Math__round" (func $imp___Math__round (param f64) (result f64)))
  (import "env" "__Math__trunc" (func $imp___Math__trunc (param f64) (result f64)))
  (import "env" "__Math__sin" (func $imp___Math__sin (param f64) (result f64)))
  (import "env" "__Math__cos" (func $imp___Math__cos (param f64) (result f64)))
  (import "env" "__Math__tan" (func $imp___Math__tan (param f64) (result f64)))
  (import "env" "__Math__asin" (func $imp___Math__asin (param f64) (result f64)))
  (import "env" "__Math__acos" (func $imp___Math__acos (param f64) (result f64)))
  (import "env" "__Math__atan" (func $imp___Math__atan (param f64) (result f64)))
  (import "env" "__Math__exp" (func $imp___Math__exp (param f64) (result f64)))
  (import "env" "__Math__log" (func $imp___Math__log (param f64) (result f64)))
  (import "env" "__Math__log2" (func $imp___Math__log2 (param f64) (result f64)))
  (import "env" "__Math__log10" (func $imp___Math__log10 (param f64) (result f64)))
  (import "env" "__Math__pow" (func $imp___Math__pow (param f64 f64) (result f64)))
  (import "env" "__Math__min" (func $imp___Math__min (param f64 f64) (result f64)))
  (import "env" "__Math__max" (func $imp___Math__max (param f64 f64) (result f64)))
  (import "env" "__Math__random" (func $imp___Math__random (result f64)))
  (import "env" "__alert" (func $imp___alert (param i32)))
  (import "env" "printf" (func $imp_printf (param f64 f64 f64 f64 f64 f64 f64 f64) (result i32)))

  (memory $mem 1)

  (table $fn_table 1 funcref)

  ;; global __stack_ptr
  (global $__stack_ptr (mut i32) (i32.const 1024))

  (data (i32.const 0) "sqrt(2) = %.4f\0a\00")
  (data (i32.const 16) "hello\00")

  (elem (table $fn_table) (i32.const 0) func $main)

  ;; function main
  (func $main (result i32)
    i32.const 0
    f64.convert_i32_s
    f64.const 2
    call $imp___Math__sqrt
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 16
    call $imp___console__log
    i32.const 0
    return
    i32.const 0
    return
  )

  (export "main" (func $main))
  (export "memory" (memory $mem))
)