// Auto-generated by webc – do not edit manually.
// Re-run  webc.js <source.c>  to regenerate.
'use strict';

// ---------- printf bridge (variadic C printf → process.stdout) ----------
function createPrintfHost(getMemory, write) {
  const encoder = new TextEncoder();
  function readCStr(ptr) {
    const mem = new Uint8Array(getMemory().buffer);
    let end = ptr >>> 0;
    while (end < mem.length && mem[end] !== 0) end++;
    return new TextDecoder('utf-8').decode(mem.subarray(ptr >>> 0, end));
  }
  return function printf(fmtPtr, ...vargs) {
    const fmt = readCStr(fmtPtr);
    let i = 0;
    const out = fmt.replace(/%([diouxXeEfFgGcsqp%])/g, (_, spec) => {
      if (spec === '%') return '%';
      const val = vargs[i++] ?? 0;
      switch (spec) {
        case 'd': case 'i': return String(val | 0);
        case 'u': return String(val >>> 0);
        case 'o': return (val >>> 0).toString(8);
        case 'x': return (val >>> 0).toString(16);
        case 'X': return (val >>> 0).toString(16).toUpperCase();
        case 'f': case 'F': case 'e': case 'E':
        case 'g': case 'G': return Number(val).toString();
        case 'c': return String.fromCharCode(val & 0xff);
        case 's': return readCStr(val);
        case 'p': return '0x' + (val >>> 0).toString(16);
        default:  return _;
      }
    });
    (write || (s => process.stdout.write(s)))(out);
    return out.length;
  };
}

// ---------- host-extern wrappers (auto-generated from source) ----------
const _buildHostEnv = // Auto-generated host env – do not edit manually
(function buildEnv(getMemory) {
  function readCString(ptr) {
    const memory = getMemory();
    if (!memory) return '';
    const mem = new Uint8Array(memory.buffer);
    const offset = ptr >>> 0; let end = offset;
    while (end < mem.length && mem[end] !== 0) end++;
    return new TextDecoder('utf-8').decode(mem.subarray(offset, end));
  }
  return {
    "__console__log": (p0) => console.log(readCString(p0)),
    "__console__error": (p0) => console.error(readCString(p0)),
    "__Math__sqrt": (p0) => Math.sqrt(p0),
    "__Math__floor": (p0) => Math.floor(p0),
  };
});

// ---------- public API ----------

/**
 * Create a WebAssembly imports object for this module.
 *
 * @param {() => WebAssembly.Memory | null} getMemory
 *   Thunk that returns the live Memory after instantiation.
 *   Pass a closure over a variable that you fill in after WebAssembly.instantiate().
 *
 * @param {{ write?: (s: string) => void }} [opts]
 *   opts.write  – custom stdout writer (default: process.stdout.write)
 *
 * @returns {WebAssembly.Imports}
 */
function createImports(getMemory, opts = {}) {
  const write = opts.write || (s => process.stdout.write(s));
  return {
    env: {
      printf: createPrintfHost(getMemory, write),
      ..._buildHostEnv(getMemory),
    }
  };
}

/**
 * Load, instantiate and run the compiled WASM module (Node.js).
 *
 * @param {string} wasmPath  – path to the .wasm file
 * @returns {Promise<number>} – exit code returned by main()
 */
async function run(wasmPath) {
  const fs   = require('fs');
  const bytes = fs.readFileSync(wasmPath);
  let memoryRef = null;
  const imports = createImports(() => memoryRef);
  const { instance } = await WebAssembly.instantiate(bytes, imports);
  memoryRef = instance.exports.memory || null;
  const entry = instance.exports.main || instance.exports.test_entry;
  if (typeof entry !== 'function') throw new Error('No main() export found');
  return entry();
}

if (typeof module !== 'undefined') {
  module.exports = { createImports, run };
}

// When executed directly (node <file>.js [wasm-path]), run main() immediately.
if (typeof require !== 'undefined' && require.main === module) {
  const _path  = require('path');
  const _wasm  = process.argv[2]
    || _path.join(__dirname, _path.basename(__filename, '.js') + '.wasm');
  run(_wasm)
    .then((code) => { process.stdout.write('\n[webc] program returned: ' + code + '\n'); process.exitCode = code; })
    .catch((err) => { console.error('[webc] ' + err.message); process.exitCode = 1; });
}
