;; Generated by MaiaC
;; Template backend: human-readable WAT
;; Style inspired by maiawasm/assembler/tests/fixtures

(module
  (import "env" "__console__log" (func $imp___console__log (param i32)))
  (import "env" "__console__error" (func $imp___console__error (param i32)))
  (import "env" "__Math__sqrt" (func $imp___Math__sqrt (param f64) (result f64)))
  (import "env" "__Math__floor" (func $imp___Math__floor (param f64) (result i32)))

  (memory $mem 1)

  (table $fn_table 1 funcref)

  ;; global __stack_ptr
  (global $__stack_ptr (mut i32) (i32.const 1024))

  (data (i32.const 0) "=== test-extern.c ===\00")
  (data (i32.const 24) "Testing __console__log: hello from C!\00")
  (data (i32.const 64) "Testing __console__error: this is an error message\00")
  (data (i32.const 116) "Math.sqrt(144) == 12  [PASS]\00")
  (data (i32.const 148) "Math.sqrt(144) != 12  [FAIL]\00")
  (data (i32.const 180) "floor(Math.sqrt(2)) == 1  [PASS]\00")
  (data (i32.const 216) "floor(Math.sqrt(2)) != 1  [FAIL]\00")
  (data (i32.const 252) "=== done ===\00")

  (elem (table $fn_table) (i32.const 0) func $main)

  ;; function main
  (func $main (result i32)
    (local $value f64)
    (local $root f64)
    (local $floored i32)
    i32.const 0
    call $imp___console__log
    i32.const 24
    call $imp___console__log
    i32.const 64
    call $imp___console__error
    f64.const 144
    local.tee $value
    drop
    local.get $value
    call $imp___Math__sqrt
    local.tee $root
    drop
    local.get $root
    call $imp___Math__floor
    i32.const 12
    i32.eq
    i32.eqz
    i32.eqz
    if
      i32.const 116
      call $imp___console__log
    else
      i32.const 148
      call $imp___console__error
    end
    f64.const 2
    local.tee $value
    drop
    local.get $value
    call $imp___Math__sqrt
    local.tee $root
    drop
    local.get $root
    call $imp___Math__floor
    i32.const 1
    i32.eq
    i32.eqz
    i32.eqz
    if
      i32.const 180
      call $imp___console__log
    else
      i32.const 216
      call $imp___console__error
    end
    i32.const 252
    call $imp___console__log
    i32.const 0
    return
    i32.const 0
    return
  )

  (export "main" (func $main))
  (export "memory" (memory $mem))
)