;; Generated by MaiaC
;; Template backend: human-readable WAT
;; Style inspired by maiawasm/assembler/tests/fixtures

(module
  (import "env" "printf" (func $imp_printf (param f64 f64 f64 f64 f64 f64 f64 f64) (result i32)))

  (memory $mem 1)

  (table $fn_table 1 funcref)

  ;; global __frame_ptr
  (global $__frame_ptr (mut i32) (i32.const 0))

  ;; global __stack_ptr
  (global $__stack_ptr (mut i32) (i32.const 1024))

  ;; global stdin
  (global $stdin (mut i32) (i32.const 0))

  ;; global stdout
  (global $stdout (mut i32) (i32.const 0))

  ;; global stderr
  (global $stderr (mut i32) (i32.const 0))

  (data (i32.const 16) "%d\0a\00")
  (data (i32.const 20) "%f\0a\00")
  (data (i32.const 24) "%c\0a\00")
  (data (i32.const 28) "%s\0a\00")

  (elem (table $fn_table) (i32.const 0) func $main)

  ;; function main
  (func $main (result i32)
    (local $__frame i32)
    (local $x i32)
    (local $y f32)
    (local $z f64)
    (local $a i32)
    (local $b i32)
    (local $__tmp_i32 i32)
    (local $__tmp_f32 f32)
    (local $__tmp_f64 f64)
    (local $__tmp_i8 i32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 32
    i32.add
    global.set $__stack_ptr
    local.get $__frame
    i32.const 17
    i32.add
    i32.const 72
    i32.store8
    local.get $__frame
    i32.const 17
    i32.add
    i32.const 1
    i32.add
    i32.const 101
    i32.store8
    local.get $__frame
    i32.const 17
    i32.add
    i32.const 2
    i32.add
    i32.const 108
    i32.store8
    local.get $__frame
    i32.const 17
    i32.add
    i32.const 3
    i32.add
    i32.const 108
    i32.store8
    local.get $__frame
    i32.const 17
    i32.add
    i32.const 4
    i32.add
    i32.const 111
    i32.store8
    local.get $__frame
    i32.const 17
    i32.add
    i32.const 5
    i32.add
    i32.const 32
    i32.store8
    local.get $__frame
    i32.const 17
    i32.add
    i32.const 6
    i32.add
    i32.const 87
    i32.store8
    local.get $__frame
    i32.const 17
    i32.add
    i32.const 7
    i32.add
    i32.const 111
    i32.store8
    local.get $__frame
    i32.const 17
    i32.add
    i32.const 8
    i32.add
    i32.const 114
    i32.store8
    local.get $__frame
    i32.const 17
    i32.add
    i32.const 9
    i32.add
    i32.const 108
    i32.store8
    local.get $__frame
    i32.const 17
    i32.add
    i32.const 10
    i32.add
    i32.const 100
    i32.store8
    local.get $__frame
    i32.const 17
    i32.add
    i32.const 11
    i32.add
    i32.const 0
    i32.store8
    local.get $__frame
    i32.const 0
    i32.add
    i32.const 1
    local.set $__tmp_i32
    local.get $__tmp_i32
    i32.store
    local.get $__tmp_i32
    drop
    local.get $__frame
    i32.const 4
    i32.add
    i32.const 2
    f32.convert_i32_s
    local.set $__tmp_f32
    local.get $__tmp_f32
    f32.store
    local.get $__tmp_f32
    drop
    local.get $__frame
    i32.const 8
    i32.add
    i32.const 3
    f64.convert_i32_s
    local.set $__tmp_f64
    local.get $__tmp_f64
    f64.store
    local.get $__tmp_f64
    drop
    local.get $__frame
    i32.const 16
    i32.add
    i32.const 65
    local.set $__tmp_i8
    local.get $__tmp_i8
    i32.store8
    local.get $__tmp_i8
    drop
    i32.const 16
    f64.convert_i32_s
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 20
    f64.convert_i32_s
    local.get $__frame
    i32.const 4
    i32.add
    f32.load
    f64.promote_f32
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 20
    f64.convert_i32_s
    local.get $__frame
    i32.const 8
    i32.add
    f64.load
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 24
    f64.convert_i32_s
    local.get $__frame
    i32.const 16
    i32.add
    i32.load8_u
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 28
    f64.convert_i32_s
    local.get $__frame
    i32.const 17
    i32.add
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
  )

  (export "main" (func $main))
  (export "memory" (memory $mem))
  (export "__frame_ptr" (global $__frame_ptr))
  (export "__stack_ptr" (global $__stack_ptr))
  (export "stdin" (global $stdin))
  (export "stdout" (global $stdout))
  (export "stderr" (global $stderr))
)