;; Generated by MaiaC
;; Template backend: human-readable WAT
;; Style inspired by maiawasm/assembler/tests/fixtures

(module
  (import "env" "printf" (func $imp_printf (param f64 f64 f64 f64 f64 f64 f64 f64) (result i32)))

  (memory $mem 1)

  (table $fn_table 1 funcref)

  ;; global __frame_ptr
  (global $__frame_ptr (mut i32) (i32.const 0))

  ;; global __stack_ptr
  (global $__stack_ptr (mut i32) (i32.const 1024))

  ;; global stdin
  (global $stdin (mut i32) (i32.const 0))

  ;; global stdout
  (global $stdout (mut i32) (i32.const 0))

  ;; global stderr
  (global $stderr (mut i32) (i32.const 0))

  (data (i32.const 16) "a + b = %d\0a\00")
  (data (i32.const 28) "a - b = %d\0a\00")
  (data (i32.const 40) "a * b = %d\0a\00")
  (data (i32.const 52) "a / b = %d\0a\00")
  (data (i32.const 64) "a %% b = %d\0a\00")
  (data (i32.const 80) "a < b = %d\0a\00")
  (data (i32.const 92) "a <= b = %d\0a\00")
  (data (i32.const 108) "a > b = %d\0a\00")
  (data (i32.const 120) "a >= b = %d\0a\00")
  (data (i32.const 136) "a == b = %d\0a\00")
  (data (i32.const 152) "a != b = %d\0a\00")
  (data (i32.const 168) "a && b = %d\0a\00")
  (data (i32.const 184) "a || b = %d\0a\00")
  (data (i32.const 200) "a = %d\0a\00")
  (data (i32.const 208) "b = %d\0a\00")

  (elem (table $fn_table) (i32.const 0) func $main)

  ;; function main
  (func $main (result i32)
    (local $a i32)
    (local $b i32)
    (local $c i32)
    i32.const 1
    local.set $a
    i32.const 2
    local.set $b
    local.get $a
    local.get $b
    i32.add
    local.tee $c
    drop
    i32.const 16
    f64.convert_i32_s
    local.get $c
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    local.get $a
    local.get $b
    i32.sub
    local.tee $c
    drop
    i32.const 28
    f64.convert_i32_s
    local.get $c
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    local.get $a
    local.get $b
    i32.mul
    local.tee $c
    drop
    i32.const 40
    f64.convert_i32_s
    local.get $c
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    local.get $a
    local.get $b
    i32.div_s
    local.tee $c
    drop
    i32.const 52
    f64.convert_i32_s
    local.get $c
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    local.get $a
    local.get $b
    i32.rem_s
    local.tee $c
    drop
    i32.const 64
    f64.convert_i32_s
    local.get $c
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    local.get $a
    local.get $b
    i32.lt_s
    local.tee $c
    drop
    i32.const 80
    f64.convert_i32_s
    local.get $c
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    local.get $a
    local.get $b
    i32.le_s
    local.tee $c
    drop
    i32.const 92
    f64.convert_i32_s
    local.get $c
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    local.get $a
    local.get $b
    i32.gt_s
    local.tee $c
    drop
    i32.const 108
    f64.convert_i32_s
    local.get $c
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    local.get $a
    local.get $b
    i32.ge_s
    local.tee $c
    drop
    i32.const 120
    f64.convert_i32_s
    local.get $c
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    local.get $a
    local.get $b
    i32.eq
    local.tee $c
    drop
    i32.const 136
    f64.convert_i32_s
    local.get $c
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    local.get $a
    local.get $b
    i32.ne
    local.tee $c
    drop
    i32.const 152
    f64.convert_i32_s
    local.get $c
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 0
    local.tee $b
    drop
    local.get $a
    i32.eqz
    i32.eqz
    if (result i32)
      local.get $b
      i32.eqz
      i32.eqz
    else
      i32.const 0
    end
    local.tee $c
    drop
    i32.const 168
    f64.convert_i32_s
    local.get $c
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    local.get $a
    i32.eqz
    i32.eqz
    if (result i32)
      i32.const 1
    else
      local.get $b
      i32.eqz
      i32.eqz
    end
    local.tee $c
    drop
    i32.const 184
    f64.convert_i32_s
    local.get $c
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    local.get $a
    local.get $a
    i32.const 1
    i32.add
    local.set $a
    drop
    i32.const 200
    f64.convert_i32_s
    local.get $a
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    local.get $b
    local.get $b
    i32.const 1
    i32.sub
    local.set $b
    drop
    i32.const 208
    f64.convert_i32_s
    local.get $b
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 0
    return
    i32.const 0
    return
  )

  (export "main" (func $main))
  (export "memory" (memory $mem))
  (export "__frame_ptr" (global $__frame_ptr))
  (export "__stack_ptr" (global $__stack_ptr))
  (export "stdin" (global $stdin))
  (export "stdout" (global $stdout))
  (export "stderr" (global $stderr))
)