;; Generated by MaiaC
;; Template backend: human-readable WAT
;; Style inspired by maiawasm/assembler/tests/fixtures

(module
  (import "env" "_longjmp_unwind_js" (func $imp_longjmp (param i32 i32) (result i32)))
  (import "env" "_setjmp_capture_js" (func $imp_setjmp (param i32) (result i32)))
  (import "env" "printf" (func $imp_printf (param f64 f64 f64 f64 f64 f64 f64 f64) (result i32)))

  (memory $mem 1)

  (table $fn_table 2 funcref)

  ;; global __frame_ptr
  (global $__frame_ptr (mut i32) (i32.const 0))

  ;; global __stack_ptr
  (global $__stack_ptr (mut i32) (i32.const 1024))

  ;; global FILE
  (global $FILE (mut i32) (i32.const 0))

  ;; global fpos_t
  (global $fpos_t (mut i64) (i64.const 0))

  ;; global stdin
  (global $stdin (mut i32) (i32.const 0))

  ;; global stdout
  (global $stdout (mut i32) (i32.const 0))

  ;; global stderr
  (global $stderr (mut i32) (i32.const 0))

  ;; global jmp_buf
  (global $jmp_buf (mut i32) (i32.const 0))

  ;; global env
  (global $env (mut i32) (i32.const 0))

  (data (i32.const 16) "PASS setjmp_longjmp\0a\00")
  (data (i32.const 40) "ALL PASS\0a\00")

  (elem (table $fn_table) (i32.const 0) func $dive $main)

  ;; function dive
  (func $dive (param $n i32) (result i32)
    local.get $n
    i32.const 0
    i32.eq
    i32.eqz
    i32.eqz
    if
      global.get $env
      i32.const 7
      call $imp_longjmp
      drop
    end
    local.get $n
    i32.const 1
    i32.sub
    call $dive
    return
    i32.const 0
    return
  )

  ;; function main
  (func $main (result i32)
    (local $rc i32)
    global.get $env
    call $imp_setjmp
    local.tee $rc
    drop
    local.get $rc
    i32.const 0
    i32.eq
    i32.eqz
    i32.eqz
    if
      i32.const 2
      call $dive
      drop
    else
      local.get $rc
      i32.const 7
      i32.eq
      i32.eqz
      i32.eqz
      if
        i32.const 16
        f64.convert_i32_s
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        call $imp_printf
        drop
        i32.const 40
        f64.convert_i32_s
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        call $imp_printf
        drop
        i32.const 0
        return
      end
    end
    i32.const 99
    return
    i32.const 0
    return
  )

  (export "dive" (func $dive))
  (export "main" (func $main))
  (export "memory" (memory $mem))
  (export "__frame_ptr" (global $__frame_ptr))
  (export "__stack_ptr" (global $__stack_ptr))
  (export "FILE" (global $FILE))
  (export "fpos_t" (global $fpos_t))
  (export "stdin" (global $stdin))
  (export "stdout" (global $stdout))
  (export "stderr" (global $stderr))
  (export "jmp_buf" (global $jmp_buf))
  (export "env" (global $env))
)