;; Generated by MaiaC
;; Template backend: human-readable WAT
;; Style inspired by maiawasm/assembler/tests/fixtures

(module
  (import "env" "printf" (func $imp_printf (param f64 f64 f64 f64 f64 f64 f64 f64) (result i32)))

  (memory $mem 1)

  (table $fn_table 5 funcref)

  ;; global __frame_ptr
  (global $__frame_ptr (mut i32) (i32.const 0))

  ;; global __stack_ptr
  (global $__stack_ptr (mut i32) (i32.const 1024))

  ;; global stdin
  (global $stdin (mut i32) (i32.const 0))

  ;; global stdout
  (global $stdout (mut i32) (i32.const 0))

  ;; global stderr
  (global $stderr (mut i32) (i32.const 0))

  (data (i32.const 16) "Hello World!\0a\00")
  (data (i32.const 32) "%s\0a\00")
  (data (i32.const 36) "Hi there!\00")
  (data (i32.const 48) "The square of 5 is %g.\0a\00")
  (data (i32.const 72) "The cube of 2 is %g.\0a\00")

  (elem (table $fn_table) (i32.const 0) func $hello_world $display_message $square $power $main)

  ;; function hello_world
  (func $hello_world
    i32.const 16
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
  )

  ;; function display_message
  (func $display_message (param $msg i32)
    (local $__frame i32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 8
    i32.add
    global.set $__stack_ptr
    local.get $__frame
    i32.const 0
    i32.add
    local.get $msg
    i32.store
    i32.const 32
    f64.convert_i32_s
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
  )

  ;; function square
  (func $square (param $x f32) (result f32)
    local.get $x
    local.get $x
    f32.mul
    return
    f32.const 0
    return
  )

  ;; function power
  (func $power (param $x f32) (param $y i32) (result f32)
    (local $i i32)
    (local $p f32)
    i32.const 1
    f32.convert_i32_s
    local.tee $p
    drop
    i32.const 0
    local.tee $i
    drop
    block $power_for_exit_0
      loop $power_for_loop_2
        local.get $i
        local.get $y
        i32.lt_s
        i32.eqz
        i32.eqz
        i32.eqz
        br_if $power_for_exit_0
        block $power_for_continue_1
          local.get $p
          local.get $x
          f32.mul
          local.tee $p
          drop
        end
        local.get $i
        local.get $i
        i32.const 1
        i32.add
        local.set $i
        drop
        br $power_for_loop_2
      end
    end
    local.get $p
    return
    f32.const 0
    return
  )

  ;; function main
  (func $main (result i32)
    call $hello_world
    i32.const 36
    call $display_message
    i32.const 48
    f64.convert_i32_s
    i32.const 5
    f32.convert_i32_s
    call $square
    f64.promote_f32
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 72
    f64.convert_i32_s
    i32.const 2
    f32.convert_i32_s
    i32.const 3
    call $power
    f64.promote_f32
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 0
    return
    i32.const 0
    return
  )

  (export "hello_world" (func $hello_world))
  (export "display_message" (func $display_message))
  (export "square" (func $square))
  (export "power" (func $power))
  (export "main" (func $main))
  (export "memory" (memory $mem))
  (export "__frame_ptr" (global $__frame_ptr))
  (export "__stack_ptr" (global $__stack_ptr))
  (export "stdin" (global $stdin))
  (export "stdout" (global $stdout))
  (export "stderr" (global $stderr))
)