;; Generated by MaiaC
;; Template backend: human-readable WAT
;; Style inspired by maiawasm/assembler/tests/fixtures

(module
  (import "env" "printf" (func $imp_printf (param f64 f64 f64 f64 f64 f64 f64 f64) (result i32)))
  (import "env" "scanf" (func $imp_scanf (param i32 i32 i32 i32 i32 i32 i32 i32) (result i32)))

  (memory $mem 1)

  (table $fn_table 1 funcref)

  ;; global __frame_ptr
  (global $__frame_ptr (mut i32) (i32.const 0))

  ;; global __stack_ptr
  (global $__stack_ptr (mut i32) (i32.const 1024))

  ;; global stdin
  (global $stdin (mut i32) (i32.const 0))

  ;; global stdout
  (global $stdout (mut i32) (i32.const 0))

  ;; global stderr
  (global $stderr (mut i32) (i32.const 0))

  (data (i32.const 16) "Enter the initial position of the object in m: \00")
  (data (i32.const 64) "%f\00")
  (data (i32.const 68) "Enter the velocity of the object in m/s: \00")
  (data (i32.const 112) "Enter the elapsed time in s: \00")
  (data (i32.const 144) "Current position of the object: %.2f m.\0a\00")

  (elem (table $fn_table) (i32.const 0) func $main)

  ;; function main
  (func $main (result i32)
    (local $__frame i32)
    (local $position f32)
    (local $initial_position f32)
    (local $velocity f32)
    (local $time f32)
    (local $__tmp_f32 f32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 16
    i32.add
    global.set $__stack_ptr
    i32.const 16
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 64
    local.get $__frame
    i32.const 4
    i32.add
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    call $imp_scanf
    drop
    i32.const 68
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 64
    local.get $__frame
    i32.const 8
    i32.add
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    call $imp_scanf
    drop
    i32.const 112
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 64
    local.get $__frame
    i32.const 12
    i32.add
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    call $imp_scanf
    drop
    local.get $__frame
    i32.const 0
    i32.add
    local.get $__frame
    i32.const 4
    i32.add
    f32.load
    local.get $__frame
    i32.const 8
    i32.add
    f32.load
    local.get $__frame
    i32.const 12
    i32.add
    f32.load
    f32.mul
    f32.add
    local.set $__tmp_f32
    local.get $__tmp_f32
    f32.store
    local.get $__tmp_f32
    drop
    i32.const 144
    f64.convert_i32_s
    local.get $__frame
    i32.const 0
    i32.add
    f32.load
    f64.promote_f32
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
  )

  (export "main" (func $main))
  (export "memory" (memory $mem))
  (export "__frame_ptr" (global $__frame_ptr))
  (export "__stack_ptr" (global $__stack_ptr))
  (export "stdin" (global $stdin))
  (export "stdout" (global $stdout))
  (export "stderr" (global $stderr))
)