;; Generated by MaiaC
;; Template backend: human-readable WAT
;; Style inspired by maiawasm/assembler/tests/fixtures

(module
  (import "env" "printf" (func $imp_printf (param f64 f64 f64 f64 f64 f64 f64 f64) (result i32)))

  (type (func (param i32 i32) (result i32)))

  (memory $mem 1)

  (table $fn_table 5 funcref)

  ;; global __frame_ptr
  (global $__frame_ptr (mut i32) (i32.const 0))

  ;; global __stack_ptr
  (global $__stack_ptr (mut i32) (i32.const 1024))

  ;; global stdin
  (global $stdin (mut i32) (i32.const 0))

  ;; global stdout
  (global $stdout (mut i32) (i32.const 0))

  ;; global stderr
  (global $stderr (mut i32) (i32.const 0))

  (data (i32.const 16) "%s attacks %s and deals %d damage.\0a\00")
  (data (i32.const 52) "Status -> %s: %d HP | %s: %d HP\0a\00")
  (data (i32.const 88) "=== The Last Kingdom (C89 Edition) ===\0a\00")
  (data (i32.const 128) "Arthur\00")
  (data (i32.const 136) "Tiamat\00")
  (data (i32.const 144) "\0aTurn %d\0a\00")
  (data (i32.const 156) "\0a=== Battle Result ===\0a\00")
  (data (i32.const 180) "%s wins!\0a\00")

  (elem (table $fn_table) (i32.const 0) func $copy_text $default_attack $character_init $print_status $main)

  ;; function copy_text
  (func $copy_text (param $dest i32) (param $src i32) (param $max_len i32)
    (local $__frame i32)
    (local $i i32)
    (local $__tmp_i32 i32)
    (local $__tmp_i8 i32)
    (local $__tmp_addr i32)
    (local $__tmp_old_i32 i32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 16
    i32.add
    global.set $__stack_ptr
    local.get $__frame
    i32.const 0
    i32.add
    local.get $dest
    i32.store
    local.get $__frame
    i32.const 4
    i32.add
    local.get $src
    i32.store
    local.get $__frame
    i32.const 8
    i32.add
    local.get $max_len
    i32.store
    local.get $__frame
    i32.const 12
    i32.add
    i32.const 0
    local.set $__tmp_i32
    local.get $__tmp_i32
    i32.store
    local.get $__tmp_i32
    drop
    block $copy_text_for_exit_0
      loop $copy_text_for_loop_2
        local.get $__frame
        i32.const 12
        i32.add
        i32.load
        local.get $__frame
        i32.const 8
        i32.add
        i32.load
        i32.const 1
        i32.sub
        i32.lt_s
        i32.eqz
        i32.eqz
        if (result i32)
          local.get $__frame
          i32.const 4
          i32.add
          i32.load
          local.get $__frame
          i32.const 12
          i32.add
          i32.load
          i32.const 1
          i32.mul
          i32.add
          i32.load8_u
          i32.eqz
          i32.eqz
        else
          i32.const 0
        end
        i32.eqz
        i32.eqz
        i32.eqz
        br_if $copy_text_for_exit_0
        block $copy_text_for_continue_1
          local.get $__frame
          i32.const 0
          i32.add
          i32.load
          local.get $__frame
          i32.const 12
          i32.add
          i32.load
          i32.const 1
          i32.mul
          i32.add
          local.get $__frame
          i32.const 4
          i32.add
          i32.load
          local.get $__frame
          i32.const 12
          i32.add
          i32.load
          i32.const 1
          i32.mul
          i32.add
          i32.load8_u
          local.set $__tmp_i8
          local.get $__tmp_i8
          i32.store8
          local.get $__tmp_i8
          drop
        end
        local.get $__frame
        i32.const 12
        i32.add
        local.tee $__tmp_addr
        i32.load
        local.tee $__tmp_old_i32
        i32.const 1
        i32.add
        local.set $__tmp_i32
        local.get $__tmp_addr
        local.get $__tmp_i32
        i32.store
        local.get $__tmp_old_i32
        drop
        br $copy_text_for_loop_2
      end
    end
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    local.get $__frame
    i32.const 12
    i32.add
    i32.load
    i32.const 1
    i32.mul
    i32.add
    i32.const 0
    local.set $__tmp_i8
    local.get $__tmp_i8
    i32.store8
    local.get $__tmp_i8
    drop
  )

  ;; function default_attack
  (func $default_attack (param $self i32) (param $enemy i32) (result i32)
    (local $__frame i32)
    (local $damage i32)
    (local $__tmp_i32 i32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 104
    i32.add
    global.set $__stack_ptr
    local.get $__frame
    i32.const 0
    i32.add
    local.get $self
    i32.store
    local.get $__frame
    i32.const 48
    i32.add
    local.get $enemy
    i32.store
    local.get $__frame
    i32.const 96
    i32.add
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 36
    i32.add
    i32.load
    local.get $__frame
    i32.const 48
    i32.add
    i32.load
    i32.const 40
    i32.add
    i32.load
    i32.sub
    local.set $__tmp_i32
    local.get $__tmp_i32
    i32.store
    local.get $__tmp_i32
    drop
    local.get $__frame
    i32.const 96
    i32.add
    i32.load
    i32.const 1
    i32.lt_s
    i32.eqz
    i32.eqz
    if
      local.get $__frame
      i32.const 96
      i32.add
      i32.const 1
      local.set $__tmp_i32
      local.get $__tmp_i32
      i32.store
      local.get $__tmp_i32
      drop
    end
    local.get $__frame
    i32.const 48
    i32.add
    i32.load
    i32.const 32
    i32.add
    local.get $__frame
    i32.const 48
    i32.add
    i32.load
    i32.const 32
    i32.add
    i32.load
    local.get $__frame
    i32.const 96
    i32.add
    i32.load
    i32.sub
    local.set $__tmp_i32
    local.get $__tmp_i32
    i32.store
    local.get $__tmp_i32
    drop
    local.get $__frame
    i32.const 48
    i32.add
    i32.load
    i32.const 32
    i32.add
    i32.load
    i32.const 0
    i32.lt_s
    i32.eqz
    i32.eqz
    if
      local.get $__frame
      i32.const 48
      i32.add
      i32.load
      i32.const 32
      i32.add
      i32.const 0
      local.set $__tmp_i32
      local.get $__tmp_i32
      i32.store
      local.get $__tmp_i32
      drop
    end
    i32.const 16
    f64.convert_i32_s
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 0
    i32.add
    f64.convert_i32_s
    local.get $__frame
    i32.const 48
    i32.add
    i32.load
    i32.const 0
    i32.add
    f64.convert_i32_s
    local.get $__frame
    i32.const 96
    i32.add
    i32.load
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    local.get $__frame
    i32.const 96
    i32.add
    i32.load
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
  )

  ;; function character_init
  (func $character_init (param $c i32) (param $name i32) (param $health i32) (param $attack i32) (param $defense i32)
    (local $__frame i32)
    (local $__tmp_i32 i32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 64
    i32.add
    global.set $__stack_ptr
    local.get $__frame
    i32.const 0
    i32.add
    local.get $c
    i32.store
    local.get $__frame
    i32.const 48
    i32.add
    local.get $name
    i32.store
    local.get $__frame
    i32.const 52
    i32.add
    local.get $health
    i32.store
    local.get $__frame
    i32.const 56
    i32.add
    local.get $attack
    i32.store
    local.get $__frame
    i32.const 60
    i32.add
    local.get $defense
    i32.store
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 0
    i32.add
    local.get $__frame
    i32.const 48
    i32.add
    i32.load
    i32.const 32
    call $copy_text
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 32
    i32.add
    local.get $__frame
    i32.const 52
    i32.add
    i32.load
    local.set $__tmp_i32
    local.get $__tmp_i32
    i32.store
    local.get $__tmp_i32
    drop
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 36
    i32.add
    local.get $__frame
    i32.const 56
    i32.add
    i32.load
    local.set $__tmp_i32
    local.get $__tmp_i32
    i32.store
    local.get $__tmp_i32
    drop
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 40
    i32.add
    local.get $__frame
    i32.const 60
    i32.add
    i32.load
    local.set $__tmp_i32
    local.get $__tmp_i32
    i32.store
    local.get $__tmp_i32
    drop
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 44
    i32.add
    i32.const 1
    local.set $__tmp_i32
    local.get $__tmp_i32
    i32.store
    local.get $__tmp_i32
    drop
  )

  ;; function print_status
  (func $print_status (param $a i32) (param $b i32)
    (local $__frame i32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 96
    i32.add
    global.set $__stack_ptr
    local.get $__frame
    i32.const 0
    i32.add
    local.get $a
    i32.store
    local.get $__frame
    i32.const 48
    i32.add
    local.get $b
    i32.store
    i32.const 52
    f64.convert_i32_s
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 0
    i32.add
    f64.convert_i32_s
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 32
    i32.add
    i32.load
    f64.convert_i32_s
    local.get $__frame
    i32.const 48
    i32.add
    i32.load
    i32.const 0
    i32.add
    f64.convert_i32_s
    local.get $__frame
    i32.const 48
    i32.add
    i32.load
    i32.const 32
    i32.add
    i32.load
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
  )

  ;; function main
  (func $main (result i32)
    (local $__frame i32)
    (local $knight i32)
    (local $dragon i32)
    (local $turn i32)
    (local $__tmp_i32 i32)
    (local $__tmp_addr i32)
    (local $__tmp_old_i32 i32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 104
    i32.add
    global.set $__stack_ptr
    i32.const 88
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    local.get $__frame
    i32.const 0
    i32.add
    i32.const 128
    i32.const 40
    i32.const 10
    i32.const 3
    call $character_init
    local.get $__frame
    i32.const 48
    i32.add
    i32.const 136
    i32.const 55
    i32.const 12
    i32.const 2
    call $character_init
    local.get $__frame
    i32.const 0
    i32.add
    local.get $__frame
    i32.const 48
    i32.add
    call $print_status
    local.get $__frame
    i32.const 96
    i32.add
    i32.const 1
    local.set $__tmp_i32
    local.get $__tmp_i32
    i32.store
    local.get $__tmp_i32
    drop
    block $main_while_exit_0
      loop $main_while_loop_1
        local.get $__frame
        i32.const 0
        i32.add
        i32.const 32
        i32.add
        i32.load
        i32.const 0
        i32.gt_s
        i32.eqz
        i32.eqz
        if (result i32)
          local.get $__frame
          i32.const 48
          i32.add
          i32.const 32
          i32.add
          i32.load
          i32.const 0
          i32.gt_s
          i32.eqz
          i32.eqz
        else
          i32.const 0
        end
        i32.eqz
        i32.eqz
        i32.eqz
        br_if $main_while_exit_0
        i32.const 144
        f64.convert_i32_s
        local.get $__frame
        i32.const 96
        i32.add
        i32.load
        f64.convert_i32_s
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        call $imp_printf
        drop
        local.get $__frame
        i32.const 0
        i32.add
        local.get $__frame
        i32.const 48
        i32.add
        local.get $__frame
        i32.const 0
        i32.add
        i32.const 44
        i32.add
        i32.load
        call_indirect (type 0)
        drop
        local.get $__frame
        i32.const 48
        i32.add
        i32.const 32
        i32.add
        i32.load
        i32.const 0
        i32.eq
        i32.eqz
        i32.eqz
        if
          br $main_while_exit_0
        end
        local.get $__frame
        i32.const 48
        i32.add
        local.get $__frame
        i32.const 0
        i32.add
        local.get $__frame
        i32.const 48
        i32.add
        i32.const 44
        i32.add
        i32.load
        call_indirect (type 0)
        drop
        local.get $__frame
        i32.const 0
        i32.add
        local.get $__frame
        i32.const 48
        i32.add
        call $print_status
        local.get $__frame
        i32.const 96
        i32.add
        local.tee $__tmp_addr
        i32.load
        local.tee $__tmp_old_i32
        i32.const 1
        i32.add
        local.set $__tmp_i32
        local.get $__tmp_addr
        local.get $__tmp_i32
        i32.store
        local.get $__tmp_old_i32
        drop
        br $main_while_loop_1
      end
    end
    i32.const 156
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    local.get $__frame
    i32.const 0
    i32.add
    i32.const 32
    i32.add
    i32.load
    i32.const 0
    i32.gt_s
    i32.eqz
    i32.eqz
    if
      i32.const 180
      f64.convert_i32_s
      local.get $__frame
      i32.const 0
      i32.add
      i32.const 0
      i32.add
      f64.convert_i32_s
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      call $imp_printf
      drop
    else
      i32.const 180
      f64.convert_i32_s
      local.get $__frame
      i32.const 48
      i32.add
      i32.const 0
      i32.add
      f64.convert_i32_s
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      call $imp_printf
      drop
    end
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
  )

  (export "copy_text" (func $copy_text))
  (export "default_attack" (func $default_attack))
  (export "character_init" (func $character_init))
  (export "print_status" (func $print_status))
  (export "main" (func $main))
  (export "memory" (memory $mem))
  (export "__frame_ptr" (global $__frame_ptr))
  (export "__stack_ptr" (global $__stack_ptr))
  (export "stdin" (global $stdin))
  (export "stdout" (global $stdout))
  (export "stderr" (global $stderr))
)