;; Generated by MaiaC
;; Template backend: human-readable WAT
;; Style inspired by maiawasm/assembler/tests/fixtures

(module
  (import "env" "printf" (func $imp_printf (param f64 f64 f64 f64 f64 f64 f64 f64) (result i32)))
  (import "env" "scanf" (func $imp_scanf (param i32 i32 i32 i32 i32 i32 i32 i32) (result i32)))

  (memory $mem 1)

  (table $fn_table 3 funcref)

  ;; global __frame_ptr
  (global $__frame_ptr (mut i32) (i32.const 0))

  ;; global __stack_ptr
  (global $__stack_ptr (mut i32) (i32.const 1024))

  ;; global stdin
  (global $stdin (mut i32) (i32.const 0))

  ;; global stdout
  (global $stdout (mut i32) (i32.const 0))

  ;; global stderr
  (global $stderr (mut i32) (i32.const 0))

  (data (i32.const 16) " %d\00")
  (data (i32.const 20) "\0a\00")
  (data (i32.const 24) "How many terms would you like to display? \00")
  (data (i32.const 68) "%d\00")

  (elem (table $fn_table) (i32.const 0) func $fibonacci_n $print_fibonacci_series $main)

  ;; function fibonacci_n
  (func $fibonacci_n (param $n i32) (result i32)
    local.get $n
    i32.const 1
    i32.le_s
    i32.eqz
    i32.eqz
    if
      local.get $n
      return
    end
    local.get $n
    i32.const 1
    i32.sub
    call $fibonacci_n
    local.get $n
    i32.const 2
    i32.sub
    call $fibonacci_n
    i32.add
    return
    i32.const 0
    return
  )

  ;; function print_fibonacci_series
  (func $print_fibonacci_series (param $n i32)
    (local $i i32)
    i32.const 1
    local.tee $i
    drop
    block $print_fibonacci_series_for_exit_0
      loop $print_fibonacci_series_for_loop_2
        local.get $i
        local.get $n
        i32.le_s
        i32.eqz
        i32.eqz
        i32.eqz
        br_if $print_fibonacci_series_for_exit_0
        block $print_fibonacci_series_for_continue_1
          i32.const 16
          f64.convert_i32_s
          local.get $i
          call $fibonacci_n
          f64.convert_i32_s
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          call $imp_printf
          drop
        end
        local.get $i
        local.get $i
        i32.const 1
        i32.add
        local.set $i
        drop
        br $print_fibonacci_series_for_loop_2
      end
    end
    i32.const 20
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
  )

  ;; function main
  (func $main (result i32)
    (local $__frame i32)
    (local $n i32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 8
    i32.add
    global.set $__stack_ptr
    i32.const 24
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 68
    local.get $__frame
    i32.const 0
    i32.add
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    call $imp_scanf
    drop
    i32.const 20
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    call $print_fibonacci_series
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
  )

  (export "fibonacci_n" (func $fibonacci_n))
  (export "print_fibonacci_series" (func $print_fibonacci_series))
  (export "main" (func $main))
  (export "memory" (memory $mem))
  (export "__frame_ptr" (global $__frame_ptr))
  (export "__stack_ptr" (global $__stack_ptr))
  (export "stdin" (global $stdin))
  (export "stdout" (global $stdout))
  (export "stderr" (global $stderr))
)