;; Generated by MaiaC
;; Template backend: human-readable WAT
;; Style inspired by maiawasm/assembler/tests/fixtures

(module
  (import "env" "fopen" (func $imp_fopen (param i32 i32) (result i32)))
  (import "env" "printf" (func $imp_printf (param f64 f64 f64 f64 f64 f64 f64 f64) (result i32)))
  (import "env" "fwrite" (func $imp_fwrite (param i32 i32 i32 i32) (result i32)))
  (import "env" "fflush" (func $imp_fflush (param i32) (result i32)))
  (import "env" "fseek" (func $imp_fseek (param i32 i32 i32) (result i32)))
  (import "env" "ftell" (func $imp_ftell (param i32) (result i32)))
  (import "env" "fclose" (func $imp_fclose (param i32) (result i32)))

  (memory $mem 1)

  (table $fn_table 1 funcref)

  ;; global __stack_ptr
  (global $__stack_ptr (mut i32) (i32.const 1024))

  (data (i32.const 16) "session.log\00")
  (data (i32.const 28) "a+\00")
  (data (i32.const 32) "failed to open session.log\0a\00")
  (data (i32.const 60) "run\0a\00")
  (data (i32.const 68) "session.log size now: %d bytes\0a\00")

  (elem (table $fn_table) (i32.const 0) func $main)

  ;; function main
  (func $main (result i32)
    (local $fp i32)
    (local $totalSize i64)
    i32.const 16
    i32.const 28
    call $imp_fopen
    local.tee $fp
    drop
    local.get $fp
    i32.const 0
    i32.eq
    i32.eqz
    i32.eqz
    if
      i32.const 32
      f64.convert_i32_s
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      call $imp_printf
      drop
      i32.const 1
      return
    end
    i32.const 60
    i32.const 1
    i32.const 4
    local.get $fp
    call $imp_fwrite
    drop
    local.get $fp
    call $imp_fflush
    drop
    local.get $fp
    i32.const 0
    i32.const 2
    call $imp_fseek
    drop
    local.get $fp
    call $imp_ftell
    i64.extend_i32_s
    local.tee $totalSize
    drop
    local.get $fp
    call $imp_fclose
    drop
    i32.const 68
    f64.convert_i32_s
    local.get $totalSize
    i32.wrap_i64
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    local.get $totalSize
    i32.wrap_i64
    return
    i32.const 0
    return
  )

  (export "main" (func $main))
  (export "memory" (memory $mem))
)