;; Generated by MaiaC
;; Template backend: human-readable WAT
;; Style inspired by maiawasm/assembler/tests/fixtures

(module
  (import "env" "_longjmp_unwind_js" (func $imp_longjmp (param i32 i32) (result i32)))
  (import "env" "_setjmp_capture_js" (func $imp_setjmp (param i32) (result i32)))

  (table $fn_table 2 funcref)

  ;; global jmp_buf
  (global $jmp_buf (mut i32) (i32.const 0))

  ;; global env
  (global $env (mut i32) (i32.const 0))

  (elem (table $fn_table) (i32.const 0) func $dive $main)

  ;; function dive
  (func $dive (param $n i32) (result i32)
    local.get $n
    i32.const 0
    i32.eq
    i32.eqz
    i32.eqz
    if
      global.get $env
      i32.const 7
      call $imp_longjmp
      drop
    end
    local.get $n
    i32.const 1
    i32.sub
    call $dive
    return
    i32.const 0
    return
  )

  ;; function main
  (func $main (result i32)
    (local $rc i32)
    global.get $env
    call $imp_setjmp
    local.tee $rc
    drop
    local.get $rc
    i32.const 0
    i32.ne
    i32.eqz
    i32.eqz
    if
      local.get $rc
      return
    end
    i32.const 2
    call $dive
    drop
    i32.const 99
    return
    i32.const 0
    return
  )

  (export "dive" (func $dive))
  (export "main" (func $main))
  (export "jmp_buf" (global $jmp_buf))
  (export "env" (global $env))
)