;; Generated by MaiaC
;; Template backend: human-readable WAT
;; Style inspired by maiawasm/assembler/tests/fixtures

(module
  (import "env" "time" (func $imp_time (param i32) (result i32)))
  (import "env" "clock" (func $imp_clock (result i32)))

  (memory $mem 1)

  (table $fn_table 1 funcref)

  ;; global __frame_ptr
  (global $__frame_ptr (mut i32) (i32.const 0))

  ;; global __stack_ptr
  (global $__stack_ptr (mut i32) (i32.const 1024))

  ;; global clock_t
  (global $clock_t (mut i64) (i64.const 0))

  ;; global time_t
  (global $time_t (mut i64) (i64.const 0))

  ;; global size_t
  (global $size_t (mut i32) (i32.const 0))

  (elem (table $fn_table) (i32.const 0) func $main)

  ;; function main
  (func $main (result i32)
    (local $__frame i32)
    (local $now i64)
    (local $ticks i64)
    (local $__tmp_i64 i64)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 16
    i32.add
    global.set $__stack_ptr
    local.get $__frame
    i32.const 0
    i32.add
    i32.const 0
    call $imp_time
    i64.extend_i32_s
    local.set $__tmp_i64
    local.get $__tmp_i64
    i64.store
    local.get $__tmp_i64
    drop
    local.get $__frame
    i32.const 8
    i32.add
    call $imp_clock
    i64.extend_i32_s
    local.set $__tmp_i64
    local.get $__tmp_i64
    i64.store
    local.get $__tmp_i64
    drop
    local.get $__frame
    i32.const 0
    i32.add
    i64.load
    i32.const 0
    i64.extend_i32_s
    i64.le_s
    i32.eqz
    i32.eqz
    if
      i32.const 31
      local.get $__parent_frame
      global.set $__frame_ptr
      local.get $__frame
      global.set $__stack_ptr
      return
    end
    local.get $__frame
    i32.const 8
    i32.add
    i64.load
    i32.const 0
    i64.extend_i32_s
    i64.lt_s
    i32.eqz
    i32.eqz
    if
      i32.const 32
      local.get $__parent_frame
      global.set $__frame_ptr
      local.get $__frame
      global.set $__stack_ptr
      return
    end
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
  )

  (export "main" (func $main))
  (export "memory" (memory $mem))
  (export "__frame_ptr" (global $__frame_ptr))
  (export "__stack_ptr" (global $__stack_ptr))
  (export "clock_t" (global $clock_t))
  (export "time_t" (global $time_t))
  (export "size_t" (global $size_t))
)