;; Generated by MaiaC
;; Template backend: human-readable WAT
;; Style inspired by maiawasm/assembler/tests/fixtures

(module
  (import "env" "printf" (func $imp_printf (param f64 f64 f64 f64 f64 f64 f64 f64) (result i32)))

  (memory $mem 1)

  (table $fn_table 4 funcref)

  ;; global __frame_ptr
  (global $__frame_ptr (mut i32) (i32.const 0))

  ;; global __stack_ptr
  (global $__stack_ptr (mut i32) (i32.const 1024))

  ;; global stdin
  (global $stdin (mut i32) (i32.const 0))

  ;; global stdout
  (global $stdout (mut i32) (i32.const 0))

  ;; global stderr
  (global $stderr (mut i32) (i32.const 0))

  (data (i32.const 16) "pop=%d\0a\00")

  (elem (table $fn_table) (i32.const 0) func $stack_init $stack_push $stack_pop $main)

  ;; function stack_init
  (func $stack_init (param $s i32) (result i32)
    (local $__frame i32)
    (local $__tmp_i32 i32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 40
    i32.add
    global.set $__stack_ptr
    local.get $__frame
    i32.const 0
    i32.add
    local.get $s
    i32.store
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 32
    i32.add
    i32.const 0
    local.set $__tmp_i32
    local.get $__tmp_i32
    i32.store
    local.get $__tmp_i32
    drop
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
  )

  ;; function stack_push
  (func $stack_push (param $s i32) (param $value i32) (result i32)
    (local $__frame i32)
    (local $__parent_frame i32)
    (local $__tmp_i32 i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 40
    i32.add
    global.set $__stack_ptr
    local.get $__frame
    i32.const 0
    i32.add
    local.get $s
    i32.store
    local.get $__frame
    i32.const 36
    i32.add
    local.get $value
    i32.store
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 32
    i32.add
    i32.load
    i32.const 8
    i32.ge_s
    i32.eqz
    i32.eqz
    if
      i32.const 0
      local.get $__parent_frame
      global.set $__frame_ptr
      local.get $__frame
      global.set $__stack_ptr
      return
    end
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 32
    i32.add
    i32.load
    i32.const 4
    i32.mul
    i32.add
    local.get $__frame
    i32.const 36
    i32.add
    i32.load
    local.set $__tmp_i32
    local.get $__tmp_i32
    i32.store
    local.get $__tmp_i32
    drop
    i32.const 1
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
  )

  ;; function stack_pop
  (func $stack_pop (param $s i32) (param $out i32) (result i32)
    (local $__frame i32)
    (local $__parent_frame i32)
    (local $__tmp_i32 i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 40
    i32.add
    global.set $__stack_ptr
    local.get $__frame
    i32.const 0
    i32.add
    local.get $s
    i32.store
    local.get $__frame
    i32.const 36
    i32.add
    local.get $out
    i32.store
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 32
    i32.add
    i32.load
    i32.const 0
    i32.le_s
    i32.eqz
    i32.eqz
    if
      i32.const 0
      local.get $__parent_frame
      global.set $__frame_ptr
      local.get $__frame
      global.set $__stack_ptr
      return
    end
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 32
    i32.add
    i32.load
    drop
    local.get $__frame
    i32.const 36
    i32.add
    i32.load
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 32
    i32.add
    i32.load
    i32.const 4
    i32.mul
    i32.add
    i32.load
    local.set $__tmp_i32
    local.get $__tmp_i32
    i32.store
    local.get $__tmp_i32
    drop
    i32.const 1
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
  )

  ;; function main
  (func $main (result i32)
    (local $__frame i32)
    (local $s i32)
    (local $value i32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 40
    i32.add
    global.set $__stack_ptr
    local.get $__frame
    i32.const 0
    i32.add
    call $stack_init
    drop
    local.get $__frame
    i32.const 0
    i32.add
    i32.const 10
    call $stack_push
    drop
    local.get $__frame
    i32.const 0
    i32.add
    i32.const 20
    call $stack_push
    drop
    local.get $__frame
    i32.const 0
    i32.add
    i32.const 30
    call $stack_push
    drop
    block $main_while_exit_0
      loop $main_while_loop_1
        local.get $__frame
        i32.const 0
        i32.add
        local.get $__frame
        i32.const 36
        i32.add
        call $stack_pop
        i32.eqz
        i32.eqz
        i32.eqz
        br_if $main_while_exit_0
        i32.const 16
        f64.convert_i32_s
        local.get $__frame
        i32.const 36
        i32.add
        i32.load
        f64.convert_i32_s
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        call $imp_printf
        drop
        br $main_while_loop_1
      end
    end
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
  )

  (export "stack_init" (func $stack_init))
  (export "stack_push" (func $stack_push))
  (export "stack_pop" (func $stack_pop))
  (export "main" (func $main))
  (export "memory" (memory $mem))
  (export "__frame_ptr" (global $__frame_ptr))
  (export "__stack_ptr" (global $__stack_ptr))
  (export "stdin" (global $stdin))
  (export "stdout" (global $stdout))
  (export "stderr" (global $stderr))
)