#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const WEB_CLI = path.join(ROOT, 'tools', 'webc.js');
const DEFAULT_OUT_DIR = path.join(ROOT, 'dist');
const JS_RUNTIME_HEADERS = new Set(['stdio', 'math', 'time', 'locale', 'signal']);
const BROWSER_MEMORY_FILE_STORE = path.join(ROOT, 'src', 'runtime', 'browser-memory-file-store.js');

function usage() {
  console.log([
    'Usage: node tools/create-dist.js <input.c> [options]',
    '',
    'Options:',
    '  -o, --out-dir <dir>   Output directory for distributable files (default: dist)',
    '  -n, --name <name>     Base name for generated app files (default: input file stem)',
    '  --wat                 Also include generated .wat file',
    '  -h, --help            Show this help'
  ].join('\n'));
}

function parseArgs(argv) {
  const args = argv.slice(2);
  const opts = {
    input: null,
    outDir: DEFAULT_OUT_DIR,
    name: null,
    emitWat: false,
    help: false
  };

  for (let i = 0; i < args.length; i += 1) {
    const arg = args[i];
    if (arg === '-h' || arg === '--help') {
      opts.help = true;
      continue;
    }

    if (arg === '--wat') {
      opts.emitWat = true;
      continue;
    }

    if (arg === '-o' || arg === '--out-dir') {
      i += 1;
      opts.outDir = path.resolve(args[i] || DEFAULT_OUT_DIR);
      continue;
    }

    if (arg === '-n' || arg === '--name') {
      i += 1;
      opts.name = String(args[i] || '').trim() || null;
      continue;
    }

    if (!arg.startsWith('-') && !opts.input) {
      opts.input = path.resolve(arg);
      continue;
    }

    throw new Error(`Unknown argument: ${arg}`);
  }

  return opts;
}

function extractHeaderLibraries(source) {
  const includeRegex = /^\s*#\s*include\s*[<"]([^">]+)[">]/gm;
  const names = [];
  const seen = new Set();
  let match;

  while ((match = includeRegex.exec(String(source || ''))) !== null) {
    const includePath = String(match[1] || '').trim();
    if (!includePath.toLowerCase().endsWith('.h')) {
      continue;
    }

    const name = path.basename(includePath, '.h');
    if (!name || seen.has(name)) {
      continue;
    }

    seen.add(name);
    names.push(name);
  }

  return names;
}

function copyFile(src, dst) {
  fs.mkdirSync(path.dirname(dst), { recursive: true });
  fs.copyFileSync(src, dst);
}

function writeBrowserRunner(outDir, appName) {
  const html = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${appName} Browser Runner</title>
  <style>
    :root {
      color-scheme: light;
      --bg: #f4efe8;
      --panel: #fffaf2;
      --ink: #1f1c19;
      --line: #d9cbb8;
      --accent: #9a3412;
    }
    body {
      margin: 0;
      padding: 24px;
      background: radial-gradient(circle at top, #fff7ed 0%, var(--bg) 55%, #efe4d5 100%);
      color: var(--ink);
      font: 16px/1.45 "Iowan Old Style", "Palatino Linotype", serif;
    }
    main {
      max-width: 980px;
      margin: 0 auto;
      background: color-mix(in srgb, var(--panel) 92%, white 8%);
      border: 1px solid var(--line);
      box-shadow: 0 18px 50px rgba(80, 50, 20, 0.08);
      padding: 24px;
    }
    h1 { margin-top: 0; font-size: 2rem; }
    p { margin: 0 0 16px; }
    .row { display: flex; gap: 12px; flex-wrap: wrap; margin-bottom: 16px; }
    button {
      border: 0;
      background: var(--accent);
      color: white;
      padding: 10px 16px;
      cursor: pointer;
      font: inherit;
    }
    label { display: inline-flex; align-items: center; gap: 8px; }
    pre {
      min-height: 280px;
      margin: 0;
      padding: 16px;
      white-space: pre-wrap;
      background: #201a17;
      color: #f8efe2;
      overflow: auto;
    }
    .muted { color: #6b6258; }
  </style>
</head>
<body>
  <main>
    <h1>${appName}</h1>
    <p>Browser runner generated by MaiaC distribution packaging. StdIO file persistence is backed by <code>localStorage</code>.</p>
    <div class="row">
      <button id="run">Run</button>
      <button id="clear-vfs">Clear VFS</button>
      <label><input id="persist-vfs" type="checkbox" checked> Persist stdio VFS in localStorage</label>
    </div>
    <p id="status" class="muted">Idle</p>
    <pre id="output"></pre>
  </main>

  <script src="./browser-memory-file-store.js"></script>
  <script src="./${appName}.js?v=${Date.now()}"></script>
  <script>
    (function () {
      const runBtn = document.getElementById('run');
      const clearBtn = document.getElementById('clear-vfs');
      const persistBox = document.getElementById('persist-vfs');
      const statusEl = document.getElementById('status');
      const outputEl = document.getElementById('output');
      const storagePrefix = 'maiac:${appName}:vfs:';

      function write(text) {
        outputEl.textContent += String(text);
        outputEl.scrollTop = outputEl.scrollHeight;
      }

      function isLongjmpLike(error) {
        if (typeof isLongjmpSignal === 'function' && isLongjmpSignal(error)) {
          return true;
        }
        return !!(error && typeof error === 'object' && error.__maiacLongjmp === true);
      }

      function runEntryWithLongjmpResume(entry, maxAttempts) {
        const attempts = Number.isInteger(maxAttempts) && maxAttempts > 0 ? maxAttempts : 32;
        for (let attempt = 0; attempt < attempts; attempt += 1) {
          try {
            return entry();
          } catch (error) {
            if (isLongjmpLike(error)) {
              continue;
            }
            throw error;
          }
        }
        throw new Error('Exceeded longjmp resume limit (' + attempts + ')');
      }

      function clearStoredFiles() {
        const keys = [];
        for (let index = 0; index < localStorage.length; index += 1) {
          const key = localStorage.key(index);
          if (key && key.indexOf(storagePrefix) === 0) {
            keys.push(key);
          }
        }
        keys.forEach((key) => localStorage.removeItem(key));
      }

      async function runApp() {
        outputEl.textContent = '';
        statusEl.textContent = 'Running...';

        try {
          const manifestResponse = await fetch('./manifest.json');
          const manifest = await manifestResponse.json();
          const response = await fetch('./${appName}.wasm');
          const bytes = await response.arrayBuffer();
          let memoryRef = null;
          const imports = createImports(
            function () { return memoryRef; },
            {
              write,
              forceMemoryFiles: true,
              memoryFileStore: persistBox.checked
                ? MaiaMemoryFileStore.createLocalStorageMemoryFileStore({ prefix: storagePrefix })
                : MaiaMemoryFileStore.createMapMemoryFileStore(new Map())
            }
          );

          const copiedLibraries = Array.isArray(manifest.copiedLibraries)
            ? manifest.copiedLibraries
            : [];

          for (const libName of copiedLibraries) {
            const libResponse = await fetch('./' + libName + '.wasm');
            const libBytes = await libResponse.arrayBuffer();
            const libInstantiated = await WebAssembly.instantiate(libBytes, imports);
            const libInstance = libInstantiated.instance || libInstantiated;

            if (!memoryRef && libInstance.exports && libInstance.exports.memory) {
              memoryRef = libInstance.exports.memory;
            }

            const env = imports && imports.env ? imports.env : {};
            Object.entries(libInstance.exports || {}).forEach(function (entry) {
              const exportName = entry[0];
              const exportValue = entry[1];
              if (typeof exportValue === 'function' && env[exportName] == null) {
                env[exportName] = exportValue;
              }
            });
          }

          const instantiated = await WebAssembly.instantiate(bytes, imports);
          const instance = instantiated.instance || instantiated;
          memoryRef = instance.exports.memory || null;

          const entry = instance.exports.main || instance.exports.test_entry;
          if (typeof entry !== 'function') {
            throw new Error('No main() or test_entry export found');
          }

          const result = runEntryWithLongjmpResume(entry);
          write('\\n[webc] program returned: ' + result + '\\n');
          statusEl.textContent = 'Done';
        } catch (error) {
          write('\\n[runner-error] ' + error.message + '\\n');
          statusEl.textContent = 'Error';
        }
      }

      runBtn.addEventListener('click', runApp);
      clearBtn.addEventListener('click', function () {
        clearStoredFiles();
        statusEl.textContent = 'Persisted VFS cleared';
      });
    })();
  </script>
</body>
</html>
`;

  fs.writeFileSync(path.join(outDir, 'browser-runner.html'), html, 'utf8');
}

function findLibraryWasm(sourceDir, libName) {
  const candidates = [
    path.join(sourceDir, `${libName}.wasm`),
    path.join(ROOT, 'lib', `${libName}.wasm`)
  ];

  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) {
      return candidate;
    }
  }

  return null;
}

function compileApp(inputPath, outBase, emitWat) {
  const args = [WEB_CLI, inputPath, '-o', outBase];
  if (emitWat) {
    args.push('--wat');
  }

  const result = spawnSync(process.execPath, args, {
    stdio: 'inherit',
    env: process.env
  });

  if (result.status !== 0) {
    throw new Error('webc compilation failed');
  }
}

function main() {
  const opts = parseArgs(process.argv);
  if (opts.help || !opts.input) {
    usage();
    process.exit(opts.help ? 0 : 1);
  }

  if (!fs.existsSync(opts.input)) {
    throw new Error(`Input file not found: ${opts.input}`);
  }

  const source = fs.readFileSync(opts.input, 'utf8');
  const sourceDir = path.dirname(opts.input);
  const appName = opts.name || path.basename(opts.input, path.extname(opts.input));
  const outDir = opts.outDir;
  const outBase = path.join(outDir, appName);

  fs.mkdirSync(outDir, { recursive: true });

  compileApp(opts.input, outBase, opts.emitWat);
  copyFile(BROWSER_MEMORY_FILE_STORE, path.join(outDir, 'browser-memory-file-store.js'));

  const linkedLibs = extractHeaderLibraries(source);
  const copiedLibs = [];
  const runtimeProvided = [];
  const missingLibs = [];

  for (const libName of linkedLibs) {
    const libSrc = findLibraryWasm(sourceDir, libName);
    if (!libSrc) {
      if (JS_RUNTIME_HEADERS.has(libName)) {
        runtimeProvided.push(libName);
      } else {
        missingLibs.push(libName);
      }
      continue;
    }

    const libDst = path.join(outDir, `${libName}.wasm`);

    if (path.resolve(libDst) === path.resolve(`${outBase}.wasm`) && path.resolve(libSrc) !== path.resolve(libDst)) {
      continue;
    }

    copyFile(libSrc, libDst);
    copiedLibs.push({ name: libName, source: libSrc, target: libDst });
  }

  const manifest = {
    generatedAt: new Date().toISOString(),
    input: opts.input,
    outDir,
    appName,
    artifacts: {
      wasm: `${appName}.wasm`,
      wrapper: `${appName}.js`,
      wat: opts.emitWat ? `${appName}.wat` : null,
      browserRunner: 'browser-runner.html',
      browserMemoryFileStore: 'browser-memory-file-store.js'
    },
    linkedLibraries: linkedLibs,
    copiedLibraries: copiedLibs.map((item) => item.name),
    runtimeProvidedHeaders: runtimeProvided,
    missingLibraries: missingLibs
  };

  fs.writeFileSync(path.join(outDir, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`, 'utf8');
  writeBrowserRunner(outDir, appName);

  console.log(`[create-dist] app wasm: ${path.join(outDir, `${appName}.wasm`)}`);
  console.log(`[create-dist] app wrapper: ${path.join(outDir, `${appName}.js`)}`);
  console.log(`[create-dist] browser runner: ${path.join(outDir, 'browser-runner.html')}`);
  console.log(`[create-dist] linked libs copied: ${copiedLibs.length}`);
  if (runtimeProvided.length > 0) {
    console.log(`[create-dist] runtime-provided headers: ${runtimeProvided.join(', ')}`);
  }
  if (missingLibs.length > 0) {
    console.log(`[create-dist] missing libs (not copied): ${missingLibs.join(', ')}`);
  }
  console.log(`[create-dist] manifest: ${path.join(outDir, 'manifest.json')}`);
}

try {
  main();
} catch (error) {
  console.error(`[create-dist] ${error.message}`);
  process.exit(1);
}
