#!/usr/bin/env node
'use strict';

/**
 * tools/webc.js
 *
 * MaiaC compiler driver: compiles a C source file and emits:
 *
 *   <output>.wasm   – binary WebAssembly module
 *   <output>.wat    – WebAssembly Text (optional, --wat)
 *   <output>.js     – JS wrapper with a ready-to-use `createImports(getMemory)`
 *                     factory that wires printf + all __extern__ host imports
 *
 * Usage:
 *   node tools/webc.js <input.c> [options]
 *
 * Options:
 *   -o <name>       Base name (without extension) for output files.
 *                   Defaults to the input filename stem.
 *                   Example: -o out/hello  →  out/hello.wasm, out/hello.js
 *   --wat           Also write the WAT source file (<output>.wat)
 *   --no-validate   Skip WAT/WASM validation
 *   --run           After compiling, run the WASM module with Node (requires
 *                   a main() export)
 *   -h, --help      Show this help message
 */

const fs   = require('fs');
const path = require('path');

const { compileSource }         = require('../compiler/c-compiler.js');
const { generateHostEnvSource } = require('./host-env-builder.js');
const { createPrintfHost }      = require('./runtime/printf-host.js');
const { buildHostEnv }          = require('./host-env-builder.js');

// ---------------------------------------------------------------------------
// Help
// ---------------------------------------------------------------------------

function usage() {
  console.log(`
Usage:
  node tools/webc.js <input.c> [options]

Options:
  -o <base>       Output base path (no extension). Default: same dir as input.
  --wat           Also emit a .wat source file alongside the .wasm
  --no-validate   Skip WAT/WASM validation step
  --run           Execute the compiled module immediately after building
  -h, --help      Show this message

Examples:
  node tools/webc.js compiler/examples/test-extern.c
  node tools/webc.js hello.c -o ./out/hello --wat --run
`.trim());
}

// ---------------------------------------------------------------------------
// Argument parsing
// ---------------------------------------------------------------------------

function parseArgs(argv) {
  const args = argv.slice(2);
  const opts = {
    input:    null,
    outBase:  null,
    wat:      false,
    validate: true,
    run:      false,
    help:     false,
  };

  for (let i = 0; i < args.length; i++) {
    const a = args[i];
    if (a === '-h' || a === '--help') { opts.help = true; }
    else if (a === '--wat')           { opts.wat = true; }
    else if (a === '--no-validate')   { opts.validate = false; }
    else if (a === '--run')           { opts.run = true; }
    else if (a === '-o') {
      i++;
      opts.outBase = args[i];
    } else if (!a.startsWith('-')) {
      opts.input = a;
    } else {
      console.error(`Unknown option: ${a}`);
      process.exit(1);
    }
  }

  return opts;
}

// ---------------------------------------------------------------------------
// JS wrapper generator
// ---------------------------------------------------------------------------

/**
 * Generates the contents of the <output>.js wrapper file.
 *
 * The emitted module exports:
 *   createImports(getMemory)  – returns a WebAssembly imports object
 *   run(wasmPath)             – convenience: loads + instantiates the .wasm
 *                               and calls main()
 */
function generateWrapper(hostImports) {
  const hostEnvSrc = generateHostEnvSource(hostImports);

  // Read the real sprintf/printf-host sources so the wrapper is self-contained
  // and handles all C format specifiers (width, precision, %lu, %.2f, etc.).
  const sprintfSrc    = fs.readFileSync(path.join(__dirname, 'runtime', 'sprintf.js'), 'utf8')
    .replace(/^'use strict';\s*/m, '')
    .replace(/\nmodule\.exports\s*=.*$/m, '');
  const printfHostSrc = fs.readFileSync(path.join(__dirname, 'runtime', 'printf-host.js'), 'utf8')
    .replace(/^'use strict';\s*/m, '')
    .replace(/^const\s*\{.*?sprintf.*?\}.*?=.*?require.*?;\s*/m, '')
    .replace(/\nmodule\.exports\s*=.*$/m, '');

  return `\
// Auto-generated by webc – do not edit manually.
// Re-run  webc.js <source.c>  to regenerate.
'use strict';

// ---------- sprintf (full C format support: width, precision, %lu, %.2f …) ----------
${sprintfSrc}

// ---------- printf bridge (variadic C printf → stdout) ----------
${printfHostSrc}

// ---------- host-extern wrappers (auto-generated from source) ----------
const _buildHostEnv = ${hostEnvSrc};

// ---------- public API ----------

/**
 * Create a WebAssembly imports object for this module.
 *
 * @param {() => WebAssembly.Memory | null} getMemory
 * @param {{ write?: (s: string) => void }} [opts]
 * @returns {WebAssembly.Imports}
 */
function createImports(getMemory, opts = {}) {
  const write = opts.write || (s => process.stdout.write(s));
  return {
    env: {
      printf: createPrintfHost({ getMemory, write }),
      ..._buildHostEnv(getMemory),
    }
  };
}

/**
 * Load, instantiate and run the compiled WASM module (Node.js).
 *
 * @param {string} wasmPath  – path to the .wasm file
 * @returns {Promise<number>} – exit code returned by main()
 */
async function run(wasmPath) {
  const fs   = require('fs');
  const bytes = fs.readFileSync(wasmPath);
  let memoryRef = null;
  const imports = createImports(() => memoryRef);
  const { instance } = await WebAssembly.instantiate(bytes, imports);
  memoryRef = instance.exports.memory || null;
  const entry = instance.exports.main || instance.exports.test_entry;
  if (typeof entry !== 'function') throw new Error('No main() export found');
  return entry();
}

if (typeof module !== 'undefined') {
  module.exports = { createImports, run };
}

// When executed directly (node <file>.js [wasm-path]), run main() immediately.
if (typeof require !== 'undefined' && require.main === module) {
  const _path  = require('path');
  const _wasm  = process.argv[2]
    || _path.join(__dirname, _path.basename(__filename, '.js') + '.wasm');
  run(_wasm)
    .then((code) => { process.stdout.write('\\n[webc] program returned: ' + code + '\\n'); process.exitCode = code; })
    .catch((err) => { console.error('[webc] ' + err.message); process.exitCode = 1; });
}
`;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  const opts = parseArgs(process.argv);

  if (opts.help) { usage(); return; }
  if (!opts.input) { usage(); process.exit(1); }

  const inputPath = path.resolve(opts.input);
  if (!fs.existsSync(inputPath)) {
    console.error(`Error: file not found: ${inputPath}`);
    process.exit(1);
  }

  // Derive output base path
  const stem    = path.basename(inputPath, path.extname(inputPath));
  const outBase = opts.outBase
    ? path.resolve(opts.outBase)
    : path.join(path.dirname(inputPath), stem);

  // Ensure output directory exists
  const outDir = path.dirname(outBase);
  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

  const wasmOut = outBase + '.wasm';
  const watOut  = outBase + '.wat';
  const jsOut   = outBase + '.js';

  // ------------------------------------------------------------------
  // Compile
  // ------------------------------------------------------------------
  const source = fs.readFileSync(inputPath, 'utf8');

  let result;
  try {
    result = compileSource(source, {
      sourcePath: inputPath,
      validate:   opts.validate,
      printWat:   false,
    });
  } catch (err) {
    console.error(`[webc] Compilation error: ${err.message}`);
    process.exit(1);
  }

  if (result.validationError) {
    console.error(`[webc] Validation error: ${result.validationError.message}`);
    process.exit(1);
  }

  if (!result.wasm) {
    console.error('[webc] Compiler did not produce a WASM binary. Re-run with --no-validate to check the WAT.');
    process.exit(1);
  }

  // ------------------------------------------------------------------
  // Write outputs
  // ------------------------------------------------------------------
  fs.writeFileSync(wasmOut, Buffer.from(result.wasm));
  console.log(`[webc] wasm  → ${wasmOut}`);

  if (opts.wat && result.wat) {
    fs.writeFileSync(watOut, result.wat, 'utf8');
    console.log(`[webc] wat   → ${watOut}`);
  }

  const wrapperSrc = generateWrapper(result.hostImports || []);
  fs.writeFileSync(jsOut, wrapperSrc, 'utf8');
  console.log(`[webc] js    → ${jsOut}`);

  // ------------------------------------------------------------------
  // Optionally run
  // ------------------------------------------------------------------
  if (opts.run) {
    console.log('[webc] running...');
    let memoryRef = null;
    const hostEnv = buildHostEnv(result.hostImports, { getMemory: () => memoryRef });
    const imports = {
      env: {
        printf: createPrintfHost({
          getMemory: () => memoryRef,
          write: (text) => process.stdout.write(String(text)),
        }),
        ...hostEnv,
      }
    };
    const bytes = Buffer.from(result.wasm);
    const { instance } = await WebAssembly.instantiate(bytes, imports);
    memoryRef = instance.exports.memory || null;
    const entry = instance.exports.main || instance.exports.test_entry;
    if (typeof entry !== 'function') {
      console.error('[webc] No main() export found in compiled module');
      process.exit(1);
    }
    const exitCode = entry();
    process.stdout.write(`\n[webc] program returned: ${exitCode}\n`);
    process.exitCode = exitCode;
  }
}

main().catch((err) => {
  console.error(`[webc] ${err.message}`);
  process.exit(1);
});
