;; Generated by MaiaC
;; Template backend: human-readable WAT
;; Style inspired by maiawasm/assembler/tests/fixtures

(module
  (import "env" "printf" (func $imp_printf (param f64 f64 f64 f64 f64 f64 f64 f64) (result i32)))
  (import "env" "scanf" (func $imp_scanf (param i32 i32 i32 i32 i32 i32 i32 i32) (result i32)))

  (memory $mem 1)

  (table $fn_table 1 funcref)

  ;; global __frame_ptr
  (global $__frame_ptr (mut i32) (i32.const 0))

  ;; global __stack_ptr
  (global $__stack_ptr (mut i32) (i32.const 1024))

  ;; global stdin
  (global $stdin (mut i32) (i32.const 0))

  ;; global stdout
  (global $stdout (mut i32) (i32.const 0))

  ;; global stderr
  (global $stderr (mut i32) (i32.const 0))

  (data (i32.const 16) "Enter your age: \00")
  (data (i32.const 36) "%d\00")
  (data (i32.const 40) "You are older than 18.\0a\00")
  (data (i32.const 64) "You are younger than 18.\0a\00")
  (data (i32.const 92) "You are 18 years old.\0a\00")
  (data (i32.const 116) "Enter your gender (M/F): \00")
  (data (i32.const 144) " %c\00")
  (data (i32.const 148) "You are male.\0a\00")
  (data (i32.const 164) "You are female.\0a\00")
  (data (i32.const 184) "Gender undefined.\0a\00")

  (elem (table $fn_table) (i32.const 0) func $main)

  ;; function main
  (func $main (result i32)
    (local $__frame i32)
    (local $age i32)
    (local $gender i32)
    (local $main___switch_value_1 i32)
    (local $main___switch_matched_2 i32)
    (local $__parent_frame i32)
    global.get $__frame_ptr
    local.set $__parent_frame
    global.get $__stack_ptr
    local.set $__frame
    local.get $__frame
    global.set $__frame_ptr
    global.get $__stack_ptr
    i32.const 8
    i32.add
    global.set $__stack_ptr
    i32.const 16
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 36
    local.get $__frame
    i32.const 0
    i32.add
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    call $imp_scanf
    drop
    local.get $__frame
    i32.const 0
    i32.add
    i32.load
    i32.const 18
    i32.gt_s
    i32.eqz
    i32.eqz
    if
      i32.const 40
      f64.convert_i32_s
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      call $imp_printf
      drop
    else
      local.get $__frame
      i32.const 0
      i32.add
      i32.load
      i32.const 18
      i32.lt_s
      i32.eqz
      i32.eqz
      if
        i32.const 64
        f64.convert_i32_s
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        call $imp_printf
        drop
      else
        i32.const 92
        f64.convert_i32_s
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        call $imp_printf
        drop
      end
    end
    i32.const 116
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 144
    local.get $__frame
    i32.const 4
    i32.add
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    call $imp_scanf
    drop
    local.get $__frame
    i32.const 4
    i32.add
    i32.load
    local.set $main___switch_value_1
    i32.const 0
    local.set $main___switch_matched_2
    block $main_switch_exit_0
      local.get $main___switch_matched_2
      if
        i32.const 148
        f64.convert_i32_s
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        call $imp_printf
        drop
        br $main_switch_exit_0
      else
        local.get $main___switch_value_1
        i32.const 109
        i32.eq
        local.get $main___switch_value_1
        i32.const 77
        i32.eq
        i32.or
        if
          i32.const 1
          local.set $main___switch_matched_2
          i32.const 148
          f64.convert_i32_s
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          call $imp_printf
          drop
          br $main_switch_exit_0
        end
      end
      local.get $main___switch_matched_2
      if
        i32.const 164
        f64.convert_i32_s
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        call $imp_printf
        drop
        br $main_switch_exit_0
      else
        local.get $main___switch_value_1
        i32.const 102
        i32.eq
        local.get $main___switch_value_1
        i32.const 70
        i32.eq
        i32.or
        if
          i32.const 1
          local.set $main___switch_matched_2
          i32.const 164
          f64.convert_i32_s
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          call $imp_printf
          drop
          br $main_switch_exit_0
        end
      end
      local.get $main___switch_matched_2
      if
        i32.const 184
        f64.convert_i32_s
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        call $imp_printf
        drop
      else
        i32.const 1
        if
          i32.const 1
          local.set $main___switch_matched_2
          i32.const 184
          f64.convert_i32_s
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          call $imp_printf
          drop
        end
      end
    end
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
    i32.const 0
    local.get $__parent_frame
    global.set $__frame_ptr
    local.get $__frame
    global.set $__stack_ptr
    return
  )

  (export "main" (func $main))
  (export "memory" (memory $mem))
  (export "__frame_ptr" (global $__frame_ptr))
  (export "__stack_ptr" (global $__stack_ptr))
  (export "stdin" (global $stdin))
  (export "stdout" (global $stdout))
  (export "stderr" (global $stderr))
)