;; Generated by MaiaC
;; Template backend: human-readable WAT
;; Style inspired by maiawasm/assembler/tests/fixtures

(module
  (import "env" "printf" (func $imp_printf (param f64 f64 f64 f64 f64 f64 f64 f64) (result i32)))

  (memory $mem 1)

  (table $fn_table 1 funcref)

  ;; global __frame_ptr
  (global $__frame_ptr (mut i32) (i32.const 0))

  ;; global __stack_ptr
  (global $__stack_ptr (mut i32) (i32.const 1024))

  ;; global stdin
  (global $stdin (mut i32) (i32.const 0))

  ;; global stdout
  (global $stdout (mut i32) (i32.const 0))

  ;; global stderr
  (global $stderr (mut i32) (i32.const 0))

  (data (i32.const 16) "PASS if_true\0a\00")
  (data (i32.const 32) "FAIL if_true\0a\00")
  (data (i32.const 48) "FAIL if_false\0a\00")
  (data (i32.const 64) "PASS if_false\0a\00")
  (data (i32.const 80) "FAIL else_if\0a\00")
  (data (i32.const 96) "PASS else_if\0a\00")
  (data (i32.const 112) "PASS for_sum\0a\00")
  (data (i32.const 128) "PASS while_count\0a\00")
  (data (i32.const 148) "PASS do_while_count\0a\00")
  (data (i32.const 172) "FAIL switch\0a\00")
  (data (i32.const 188) "PASS switch\0a\00")
  (data (i32.const 204) "PASS switch_fallthrough\0a\00")
  (data (i32.const 232) "PASS break\0a\00")
  (data (i32.const 244) "PASS continue\0a\00")
  (data (i32.const 260) "PASS nested_break\0a\00")
  (data (i32.const 280) "PASS goto\0a\00")
  (data (i32.const 292) "ALL PASS\0a\00")

  (elem (table $fn_table) (i32.const 0) func $main)

  ;; function main
  (func $main (result i32)
    (local $x i32)
    (local $i i32)
    (local $j i32)
    (local $sum i32)
    (local $w i32)
    (local $d i32)
    (local $mode i32)
    (local $cases i32)
    (local $br i32)
    (local $cont i32)
    (local $nested i32)
    (local $jumped i32)
    (local $main___switch_value_9 i32)
    (local $main___switch_matched_10 i32)
    (local $main___switch_value_12 i32)
    (local $main___switch_matched_13 i32)
    block $set_jump
      i32.const 10
      local.tee $x
      drop
      local.get $x
      i32.const 5
      i32.gt_s
      i32.eqz
      i32.eqz
      if
        i32.const 16
        f64.convert_i32_s
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        call $imp_printf
        drop
      else
        i32.const 32
        f64.convert_i32_s
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        call $imp_printf
        drop
      end
      local.get $x
      i32.const 5
      i32.lt_s
      i32.eqz
      i32.eqz
      if
        i32.const 48
        f64.convert_i32_s
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        call $imp_printf
        drop
      else
        i32.const 64
        f64.convert_i32_s
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        call $imp_printf
        drop
      end
      local.get $x
      i32.const 5
      i32.lt_s
      i32.eqz
      i32.eqz
      if
        i32.const 80
        f64.convert_i32_s
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        call $imp_printf
        drop
      else
        local.get $x
        i32.const 10
        i32.eq
        i32.eqz
        i32.eqz
        if
          i32.const 96
          f64.convert_i32_s
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          call $imp_printf
          drop
        end
      end
      i32.const 0
      local.tee $sum
      drop
      i32.const 1
      local.tee $i
      drop
      block $main_for_exit_0
        loop $main_for_loop_2
          local.get $i
          i32.const 5
          i32.le_s
          i32.eqz
          i32.eqz
          i32.eqz
          br_if $main_for_exit_0
          block $main_for_continue_1
            local.get $sum
            local.get $i
            i32.add
            local.tee $sum
            drop
          end
          local.get $i
          i32.const 1
          i32.add
          local.tee $i
          drop
          br $main_for_loop_2
        end
      end
      local.get $sum
      i32.const 15
      i32.eq
      i32.eqz
      i32.eqz
      if
        i32.const 112
        f64.convert_i32_s
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        call $imp_printf
        drop
      end
      i32.const 0
      local.tee $w
      drop
      i32.const 0
      local.tee $i
      drop
      block $main_while_exit_3
        loop $main_while_loop_4
          local.get $w
          i32.const 4
          i32.lt_s
          i32.eqz
          i32.eqz
          i32.eqz
          br_if $main_while_exit_3
          local.get $w
          local.get $w
          i32.const 1
          i32.add
          local.set $w
          drop
          local.get $i
          local.get $i
          i32.const 1
          i32.add
          local.set $i
          drop
          br $main_while_loop_4
        end
      end
      local.get $i
      i32.const 4
      i32.eq
      i32.eqz
      i32.eqz
      if
        i32.const 128
        f64.convert_i32_s
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        call $imp_printf
        drop
      end
      i32.const 0
      local.tee $d
      drop
      i32.const 0
      local.tee $i
      drop
      block $main_do_exit_5
        loop $main_do_loop_7
          block $main_do_continue_6
            local.get $d
            local.get $d
            i32.const 1
            i32.add
            local.set $d
            drop
            local.get $i
            local.get $i
            i32.const 1
            i32.add
            local.set $i
            drop
          end
          local.get $d
          i32.const 3
          i32.lt_s
          i32.eqz
          i32.eqz
          br_if $main_do_loop_7
        end
      end
      local.get $i
      i32.const 3
      i32.eq
      i32.eqz
      i32.eqz
      if
        i32.const 148
        f64.convert_i32_s
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        call $imp_printf
        drop
      end
      i32.const 2
      local.tee $mode
      drop
      local.get $mode
      local.set $main___switch_value_9
      i32.const 0
      local.set $main___switch_matched_10
      block $main_switch_exit_8
        local.get $main___switch_matched_10
        if
          i32.const 172
          f64.convert_i32_s
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          call $imp_printf
          drop
          br $main_switch_exit_8
        else
          local.get $main___switch_value_9
          i32.const 1
          i32.eq
          if
            i32.const 1
            local.set $main___switch_matched_10
            i32.const 172
            f64.convert_i32_s
            f64.const 0
            f64.const 0
            f64.const 0
            f64.const 0
            f64.const 0
            f64.const 0
            f64.const 0
            call $imp_printf
            drop
            br $main_switch_exit_8
          end
        end
        local.get $main___switch_matched_10
        if
          i32.const 188
          f64.convert_i32_s
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          call $imp_printf
          drop
          br $main_switch_exit_8
        else
          local.get $main___switch_value_9
          i32.const 2
          i32.eq
          if
            i32.const 1
            local.set $main___switch_matched_10
            i32.const 188
            f64.convert_i32_s
            f64.const 0
            f64.const 0
            f64.const 0
            f64.const 0
            f64.const 0
            f64.const 0
            f64.const 0
            call $imp_printf
            drop
            br $main_switch_exit_8
          end
        end
        local.get $main___switch_matched_10
        if
          i32.const 172
          f64.convert_i32_s
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          f64.const 0
          call $imp_printf
          drop
          br $main_switch_exit_8
        else
          i32.const 1
          if
            i32.const 1
            local.set $main___switch_matched_10
            i32.const 172
            f64.convert_i32_s
            f64.const 0
            f64.const 0
            f64.const 0
            f64.const 0
            f64.const 0
            f64.const 0
            f64.const 0
            call $imp_printf
            drop
            br $main_switch_exit_8
          end
        end
      end
      i32.const 0
      local.tee $cases
      drop
      i32.const 2
      local.set $main___switch_value_12
      i32.const 0
      local.set $main___switch_matched_13
      block $main_switch_exit_11
        local.get $main___switch_matched_13
        if
          local.get $cases
          local.get $cases
          i32.const 1
          i32.add
          local.set $cases
          drop
        else
          local.get $main___switch_value_12
          i32.const 1
          i32.eq
          if
            i32.const 1
            local.set $main___switch_matched_13
            local.get $cases
            local.get $cases
            i32.const 1
            i32.add
            local.set $cases
            drop
          end
        end
        local.get $main___switch_matched_13
        if
          local.get $cases
          local.get $cases
          i32.const 1
          i32.add
          local.set $cases
          drop
        else
          local.get $main___switch_value_12
          i32.const 2
          i32.eq
          if
            i32.const 1
            local.set $main___switch_matched_13
            local.get $cases
            local.get $cases
            i32.const 1
            i32.add
            local.set $cases
            drop
          end
        end
        local.get $main___switch_matched_13
        if
          local.get $cases
          local.get $cases
          i32.const 1
          i32.add
          local.set $cases
          drop
        else
          local.get $main___switch_value_12
          i32.const 3
          i32.eq
          if
            i32.const 1
            local.set $main___switch_matched_13
            local.get $cases
            local.get $cases
            i32.const 1
            i32.add
            local.set $cases
            drop
          end
        end
      end
      local.get $cases
      i32.const 2
      i32.eq
      i32.eqz
      i32.eqz
      if
        i32.const 204
        f64.convert_i32_s
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        call $imp_printf
        drop
      end
      i32.const 0
      local.tee $br
      drop
      i32.const 0
      local.tee $i
      drop
      block $main_for_exit_14
        loop $main_for_loop_16
          local.get $i
          i32.const 10
          i32.lt_s
          i32.eqz
          i32.eqz
          i32.eqz
          br_if $main_for_exit_14
          block $main_for_continue_15
            local.get $i
            i32.const 5
            i32.eq
            i32.eqz
            i32.eqz
            if
              br $main_for_exit_14
            end
            local.get $br
            local.get $br
            i32.const 1
            i32.add
            local.set $br
            drop
          end
          local.get $i
          i32.const 1
          i32.add
          local.tee $i
          drop
          br $main_for_loop_16
        end
      end
      local.get $br
      i32.const 5
      i32.eq
      i32.eqz
      i32.eqz
      if
        i32.const 232
        f64.convert_i32_s
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        call $imp_printf
        drop
      end
      i32.const 0
      local.tee $cont
      drop
      i32.const 0
      local.tee $i
      drop
      block $main_for_exit_17
        loop $main_for_loop_19
          local.get $i
          i32.const 5
          i32.lt_s
          i32.eqz
          i32.eqz
          i32.eqz
          br_if $main_for_exit_17
          block $main_for_continue_18
            local.get $i
            i32.const 2
            i32.eq
            i32.eqz
            i32.eqz
            if
              br $main_for_continue_18
            end
            local.get $cont
            local.get $cont
            i32.const 1
            i32.add
            local.set $cont
            drop
          end
          local.get $i
          i32.const 1
          i32.add
          local.tee $i
          drop
          br $main_for_loop_19
        end
      end
      local.get $cont
      i32.const 4
      i32.eq
      i32.eqz
      i32.eqz
      if
        i32.const 244
        f64.convert_i32_s
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        call $imp_printf
        drop
      end
      i32.const 0
      local.tee $nested
      drop
      i32.const 0
      local.tee $i
      drop
      block $main_for_exit_20
        loop $main_for_loop_22
          local.get $i
          i32.const 3
          i32.lt_s
          i32.eqz
          i32.eqz
          i32.eqz
          br_if $main_for_exit_20
          block $main_for_continue_21
            i32.const 0
            local.tee $j
            drop
            block $main_for_exit_23
              loop $main_for_loop_25
                local.get $j
                i32.const 4
                i32.lt_s
                i32.eqz
                i32.eqz
                i32.eqz
                br_if $main_for_exit_23
                block $main_for_continue_24
                  local.get $j
                  i32.const 2
                  i32.eq
                  i32.eqz
                  i32.eqz
                  if
                    br $main_for_exit_23
                  end
                  local.get $nested
                  local.get $nested
                  i32.const 1
                  i32.add
                  local.set $nested
                  drop
                end
                local.get $j
                i32.const 1
                i32.add
                local.tee $j
                drop
                br $main_for_loop_25
              end
            end
          end
          local.get $i
          i32.const 1
          i32.add
          local.tee $i
          drop
          br $main_for_loop_22
        end
      end
      local.get $nested
      i32.const 6
      i32.eq
      i32.eqz
      i32.eqz
      if
        i32.const 260
        f64.convert_i32_s
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        f64.const 0
        call $imp_printf
        drop
      end
      i32.const 0
      local.tee $jumped
      drop
      br $set_jump
      i32.const 0
      i32.const 1
      i32.sub
      local.tee $jumped
      drop
    end
    i32.const 1
    local.tee $jumped
    drop
    local.get $jumped
    i32.const 1
    i32.eq
    i32.eqz
    i32.eqz
    if
      i32.const 280
      f64.convert_i32_s
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      f64.const 0
      call $imp_printf
      drop
    end
    i32.const 292
    f64.convert_i32_s
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    f64.const 0
    call $imp_printf
    drop
    i32.const 0
    return
    i32.const 0
    return
  )

  (export "main" (func $main))
  (export "memory" (memory $mem))
  (export "__frame_ptr" (global $__frame_ptr))
  (export "__stack_ptr" (global $__stack_ptr))
  (export "stdin" (global $stdin))
  (export "stdout" (global $stdout))
  (export "stderr" (global $stderr))
)